### ISSUE TITLE
Questionable Dragon Cavern Generation

### ISSUE THREAD

**Issue by Zeklo** [Alex-the-666/Ice_and_Fire#103]
There was a tier 5 dragon on the surface, so I did a little bit of exploring.
![2016-12-05_19 16 00](https://cloud.githubusercontent.com/assets/6024737/20912025/98eaef04-bb21-11e6-8ad4-79c03f27e24b.png)
Upon further investigation I discovered it was due to a dragon den spawning very close to the surface and breaking through thanks to the way a river had generated. (As seen with x-ray)
![2016-12-05_19 16 08](https://cloud.githubusercontent.com/assets/6024737/20912045/b6496a12-bb21-11e6-83dc-a7762aa45a10.png)
Since it was still underground it just seemed like bad luck with world generation, but not too far off another tier 5 was present above ground due to a similar case. 
Then, farther off was a very evident sign of near-surface generation:
![2016-12-05_19 17 06](https://cloud.githubusercontent.com/assets/6024737/20912078/edb43cf2-bb21-11e6-808a-bcbaae97d51f.png)
I can't fully tell if this is an issue or just extremely odd world gen, but it kind of seems like they should be deeper underground.

On a side note, it might just be my bad luck with world gen or intended raised chance for testing, but dragon caverns and roosts seem rather common. Especially considering the loot and danger they provide.

**Comment by PlatinumFox** [comment]
I came across a similar generation. a stage 5 dragon nest was like 10 blocks below the surface (and right near spawn) and the dragon flew up and away and I have not seen it since. I also think that they should be a bit deeper, also maybe another solution possible solution could be making stage 4 and 5 under ground nests spawn in extreme hills biomes as they are really tall and could provide more cover to the dragons nest, also it just seems more likely that if a dragon where to "go hibernate" underground it would do so in mountains.
