### ISSUE TITLE
Various problems with Dragon bone Bow ( and dragon bone arrow )

### ISSUE THREAD

**Issue by Kusark** [Alex-the-666/Ice_and_Fire#124]
Dragon bone bow can't shoot normal arrows / arrows with potion effect, are somewhat expensive to craft, and provide the same damage output as the regular bow which overall makes them useless. Also, you can't shoot dragon bone arrows from a dispenser, not a big problem but I thought I'd throw that out there.

**Comment by Alex-the-666** [comment]
1. bow is only meant to fire dragonbone arrows, working as intended;
2. arrows are special, not meant to be poisoned, working as intended;
3. Of course they are expensive, they are anti-dragon weapons! working as intended;
4. Yeah the damage is broken but I will fix w/ a commit
5. not meant to be shot from a dispenser, because only a dragonbone bow and a dragonbone arrow can work together(in order to force players to craft both); working as intended.
