### ISSUE TITLE
1.6.1 bonus damage should occur rapid

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#1312]
As I said, Wither II is the strongest wither dose, 255 wont kill any quicker, so when multiple stares at the same target, they should have extra ticking damage to the mob beside the wither effecr

**Comment by mser7** [comment]
I tried with 5 cockatrice staring at the same mob

**Comment by PCAwesomeness** [comment]
TBH, that would just make them extremely cheap.

**Comment by mser7** [comment]
It only happen if there are many cockatrice staring at a same mob, 5 cockatrices staring and the mob dont die quicker is just lame

**Comment by PCAwesomeness** [comment]
You tame them by staring at them, though. There also may or may not be many of them in the same savanna.

As their taming method requires you to let them attacking you, simply turning them into the pre-nerf Void Eye would just make them even crappier mobs than the Stymphalian birds.

**Comment by mser7** [comment]
I dont know what is "pre-nerfed Void Eye", sorry

So you are afraid of too many of them looking and you will die, why dont you try to separate one from the rest instead? That will be even more challenge to get this awesome mob on your site

Also, have you heard of rotten eggs farm that most people use instead?

**Comment by PCAwesomeness** [comment]
Primitive Mobs' Void Eyes, in addition to their ability to shoot lasers through walls, inflict Blindness and Mining Fatigue and penetrate your armor with each attack. As with many other mobs, they tend to spawn in large groups; due to this, they'd all laser you at once, causing you to automatically die and not have any chance at winning.

Daveyx0 nerfed them by making it so only one could attack at a time.

The first two sentences are basically what you're asking for the Cockatrice to become, and it's not going to be very nice (of course they can't stare through walls, but they still inflict nasty potion effects and penetrate your armor).

**Comment by mser7** [comment]
Here is the thing, void eyes and stymphalian birds can damage you even when you are looking away, while cockatrices cannot, they will try to chase you to match your line of sight, so you could use this to separate one from the rest, blindfold might also help, the real sufferer from this would be the mobs, since they are dumb and will try to face and approach the cockatrice.
