### ISSUE TITLE
Small Suggestion

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#148]
I Loaded the new version with biomes o plenty just to try things out (some one is bound to due it upon release so im just trying to think ahead) I was surprised to say everything was pretty cohesive except for a few small things.

fire dragons spawned in the ALPS biome (cold biome) (do did ice dragons which i was pleased to see)
![2017-03-26_15 28 34](https://cloud.githubusercontent.com/assets/23727270/24334702/2c82190a-123d-11e7-8dd6-804e78db163e.png)
![2017-03-26_15 28 38](https://cloud.githubusercontent.com/assets/23727270/24334703/2f93972c-123d-11e7-870e-2825d9f48205.png)

other than that i think it worked pretty well in the 20 min i tested it with biomes o plenty

**Comment by Alex-the-666** [comment]
They do that because it is registered as a mountain biome. Fire and Ice Dragons spawn in mountain biomes, regardless of temperature(though most of these biomes are cold). If we limit this the Fire dragons wont spawn on any mountain biomes since most of them are registered as cold as well as mountain. Ill look into it though, maybe a limit on the temperature(ex. finding the exact temp of the alps biome and blocking that for fire dragons)

**Comment by PlatinumFox** [comment]
Thank you for looking into it, it is just a small suggestion though and not that bothersome. I was just relieved when i loaded the world that everything looked decent and there weren't any world gen errors. because that is what i was semi-expecting lol
