### ISSUE TITLE
The request for mod to be reprinted to China player

### ISSUE THREAD

**Issue by bucketBrian** [Alex-the-666/Ice_and_Fire#1490]
Hallo, I'm an Chinese player, @ETStarLight hasn't been online since December 2018, so I want to replace him to introduce your mod to Chinese player. For this I will create a new Chinese post to replace old post. And I also will NOT take any credits of the mod and all the link will direct to your official website. I need your permission to do this, so are you ok with that?
And I also join your Discord that I can Know the news about your mod!;)

**Comment by yqmtat** [comment]
我联系过汉化的海东了，他表示游戏里的内容有在做了，但是是翻译文件写错名字读取不到有点问题所以等待下个版本的合并，另外作者和海东有私聊，所以没有在github上更新日志，最近的一次汉化文件提交在3月份，而且目前这是一个两人团队，其中的另一个人贡献了大量的错误翻译，所以不要着急，给海东一些时间（作者似乎不怎么看issues，悲）

**Comment by yqmtat** [comment]
您的这个英语也不怎么样，我觉得作者也不会放心接受您的汉化文件的
I'm an Chinese player→a Chinese player
replace sth.一般是替代某物，给财产和事物更新换代，没有replace 谁 to 干什么事 的用法
Chinese post→ a post in Chinese或者 a post of Chinese forum表意不明
also will虽然语法上确实没错，但是整个英语网站上找不到一个用这个词组的例句呢，这么中式的表达真的ok吗
all the link→links 复数，最基本的
direct是一个形容词，并不是动词，will direct to是什么用法呢？
 so are you ok with that?我就直说了吧，我觉得很不ok
I also join 一般现在时在这里有什么意义呢？你是一直加入还是说你加入是一个亘古不变的客观规律？
your Discord that I can Know the news about your mod，that接在名词后面想必是一个定语从句了，但是我能知道有关你mod的新闻完全没办法修饰Discord，你是想说我能知道有关你mod的新闻的Discord吗？整个Discord平台加公司就是只起到我能知道有关你mod的新闻的作用吗？请在that 之前加so 来表达这不是定语从句而是状语从句，so that我能知道有关你mod的新闻√
您这个英文水平还是回炉重造再说吧

**Comment by bucketBrian** [comment]
@yqmtat 唉，我是真的羞愧难当。不过我其实也不过是来向作者要官方授权而已，你如果逛mcbbs的话应该也知道那个二搬贴吧。

**Comment by yqmtat** [comment]
这个mod还不是最终版，作者还在更新，既然原po不愿意继续搬，那你来要授权还不如直接找原po主etstarlight删帖，您这样又跟二搬有什么区别呢，我觉得既然放在mcbbs的帖子都没有盈利目的，无非就是或早或晚，您不如再等一等，这么着急干嘛呢

**Comment by AlexModGuy** [comment]
we will accept any translations made through a pull request. regardless of who is doing it.
