### ISSUE TITLE
Particle Spawn Causing Crash

### ISSUE THREAD

**Issue by ReportBot9009** [Alex-the-666/Ice_and_Fire#1500]
I and other people are getting this crash with certain mods when the new Phosphor mod is loaded, and it seems the mod author of Phosphor knows what is happening.

Here is the link to crash report and conversation:

https://gitea.gildedgames.com/jellysquid/Phosphor/issues/5

**Comment by Zeksy** [comment]
With having read the link it confirms what I've been having as well-

I also have 'Ice and Fire' with 'The Aether' being a very recent addition to my personal pack, this exact crash only just now happening after installing 'The Aether'

On all the crash reports it reads "ParticlePixieDust" under 'Particle being rendered' being what was trying to be rendered in.

**Comment by Xorbah** [comment]
Pixie dust particles stem from Ice and Fire. Maybe Aether is conflicting
with it someho when phosphor is installed.

**Comment by Zeksy** [comment]
The problem with myself at least is that: I don't have Phosphor installed in my pack

I wrote that it confirms my case because as the link showed: Jellysquid has been getting this same report from those in The Aether mod discord, which the mod itself is a very recent addition for me.

Considering the particle that caused the crash I felt it was best to look here first, but I will see about leaving a report on The Aether mod as well.

**Comment by AlexModGuy** [comment]
fixed
