### ISSUE TITLE
Server crash due to tick lag, seems to be caused by Myrmex

### ISSUE THREAD

**Issue by katubug** [Alex-the-666/Ice_and_Fire#1531]
Hi there! I got this crash log: https://hastebin.com/dinexaleye.sql

Is there anything I can do to prevent this crash in the future? Thanks for your time!

**Comment by Loriborn** [comment]
Hey @katubug!

It seems that unfortunately the Myrmex are very tick-intensive mobs, particularly the workers, and their AI brings even decent hardware to its knees in an MP setting. Ice and Fire isn't exactly friendly with multiplayer servers, especially those with many tick intensive mods added, such as Serene Seasons, so the current fix would simply be to disable the Myrmex spawning in the config.

This won't remove them from your world however, and if they are still affecting performance (check using /tps or TickProfiler using /profile e) then you may want to run a command to kill exclusively those entities in all loaded chunks. You'll have to repeat this command any time you revisit areas with hives but eventually they should all be cleared. 

`/kill @e[type=iceandfire:myrmex_worker]`

Simply replace "worker" with queen, sentinel, soldier, royal, and egg, to remove all the of Myrmex mobs from the world. You can even write a server macro or command block to run these commands every few minutes (as players revisit chunks where they've generated) until you're certain the mobs are removed.

As I mentioned, unfortunately Myrmex are just too complex and tick too frequently with no way to lower their tick rates. Personally, I believe that more of their AI  functions should be event based rather than tick driven, as this means that as more chunks are loaded, and more hives generate, and more Myrmex propagate, that you can get insanely low tickrates that eventually cause a server watchdog to think the server has crashed and to shut it down. I've had a server go from 20TPS to 5TPS just loading a few hives with default config settings in a jungle biome with only one or two players online loading their respective number of chunks. After /kill'ing the Myrmex, tickrate immediately shot up to 20TPS again.
