### ISSUE TITLE
MC Crash

### ISSUE THREAD

**Issue by Meikel184** [Alex-the-666/Ice_and_Fire#1565]
By thenew version of the ice and fire mod crashing my modpack allway why  ?
creating world and all go but when a dragon orsomethign in he near spawn crash and all closed
Edit: is by all versions
edit: https://pastebin.com/zs7t5ABW

**Comment by jellysquid3** [comment]
You're using an old version of Phosphor (which included with the Aether.) Ice and Fire is incompatible with old versions of Phoshpor due to a bug in their particle spawning code, but newer versions make an attempt to work around the issue. Download the latest release of Phosphor and install it alongside the Aether to update it.
