### ISSUE TITLE
Sea Serpents on Land megaissue

### ISSUE THREAD

**Issue by AlexModGuy** [Alex-the-666/Ice_and_Fire#1657]
This really isn't an issue imo, it just means that a sea serpent misplaced a landing site and got beached. happens IRL with dolphins and whales. But so many people report it as one so I may as well redirect them here.

**Comment by susantussing** [comment]
To me, most of why this is a problem is that this is entirely contrary to what I'm looking for in a platonic sea serpent.  They aren't, in mythic terms, fearsome creatures of the shallows, much less fearsome creatures of the nearby beaches (and possibly forests).  They're a threat to those who stray too far from shore.  The whole primal danger of the sea thing.  But I've had two sea serpent attacks.  One of them, I was in a boat trying to cross an ocean to the desert to the north to save the time of walking overland.  I was appropriately shaken!  The other, I was standing near (but not on) the beach on a plains biome, unaware that they could do this, and hadn't realized I was in an area where I could be attacked just because I could still see the water.  When the threat comes in the wrong place/time, creatures like this lose a lot of the fun of their mythological associations.

If they don't pose enough of a danger by only being a threat in deep waters, maybe there'd be a way to make those oceans more appealing to create a reason to risk it in the mid/late game?

Just some thoughts, I like the core idea of this but I feel like it could be way cooler.

**Comment by smoothuk** [comment]
Sea serpents? Pffff..  how about a TREE SERPENT!

[https://imgur.com/a/GPde779](https://imgur.com/a/GPde779)

**Comment by abdullahasayed** [comment]
The problem is, from my experience, is that the serpent often ends up stuck in the side of a hill or something. I think it would make more sense if they were able to go back to the water. Once stuck on land, only parts of them are visible and they become exceedingly vulnerable.
