### ISSUE TITLE
Breeding megaissue

### ISSUE THREAD

**Issue by AlexModGuy** [Alex-the-666/Ice_and_Fire#1659]

**Comment by zucaluca** [comment]
I dont know if this is the cause or if it was fixed but when I tried to breed hippogryphs -  in a lan server especially- they didn't move towards each other because the game thought they were sitting when they appeared to the player as unsat. A relog fixed it every time. Again idk if this was fixed already. Disregard if so

**Comment by ValentineBlaze** [comment]
I just tried breeding two fire dragons and nothing was happening at all.

**Comment by GooberYT** [comment]
I cannot breed any dragons I put them on wandering and give the female the potion first is that wht im supposed to do?

**Comment by AlexModGuy** [comment]
fixed
