### ISSUE TITLE
dragon glitch (not really)

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Ice_and_Fire#1665]
not really I just want it to be 69 open issues lololol

**Comment by mxnmnm** [comment]
quick alex is asleep let's reopen this issue

PS: I'm sorry little one

**Comment by mxnmnm** [comment]
And yes I am a mad lad

**Comment by mxnmnm** [comment]
It's at 68 which means I gotta reopen this veri important for the meme

**Comment by Robomnz** [comment]
Can you not this is a bug tracker not a meme tracker. The devs dont have time for your stupid memes and its just going to waste their time when they have other things to do like patch real bugs so please close this

**Comment by mxnmnm** [comment]
69 tho

**Comment by BlueWither** [comment]
stop that

**Comment by Robomnz** [comment]
Who cares honestly this is not the place for stupid memes if you want memes go on discord and post memes there because this is not the place to post memes and you posting fake bug issues on the tracker is just going to waste the devs time and i want the next update to patch as much bugs as possible and they cant do that when your posting stupid memes on the bug tracker

**Comment by Robomnz** [comment]
Now please close this

**Comment by mxnmnm** [comment]
the toughest choices require the strongest wills

**Comment by ghost** [comment]
I approve of this "issue"
