### ISSUE TITLE
Particle issue again

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#1719]
I don't know why it happened, but I noticed all particles disappeared.

**Comment by ColaLiao** [comment]
also have this problem

**Comment by stormbringerGT** [comment]
Dragon's breath is not rendering when they breath fire in the wild.

**Comment by SamuraiShogun1102** [comment]
The reason the particles disappear because too many particles have been used because I tried that when exploded lots of tnt, placed too many torches, and destroyed lots of blocks on both vanilla and modded and these particles used so much memory that Minecraft automatically disables them to improve performance.

**Comment by AlexModGuy** [comment]
fixed. i literally tested it by spawning 100 pixies and 20 sirens in a room and waited for 20 mins
