### ISSUE TITLE
dragon moved wrongly!

### ISSUE THREAD

**Issue by Platipucat** [Alex-the-666/Ice_and_Fire#1843]
when ever someont fly a dragon in the server the console would span a lot of X Dragon moved wrongly and the player will teleport
exemple :
[18:21:14] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Fire Dragon moved wrongly!
[18:21:14] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Fire Dragon moved wrongly!
[18:21:14] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Fire Dragon moved wrongly!
[18:21:14] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Fire Dragon moved wrongly!
is there a way to fix this?

**Comment by katubug** [comment]
My players and I are having the same issue. The player attempts to mount the dragon and gets teleported up into the air while the dragon appears to stay on the ground.

Then the console gets absolutely *spammed* with "moved wrongly" errors. Like, she was on the dragon for maybe 10 seconds and it was like 4-5 pages of the error.

The issue seems to occur with amphitheres as well. We haven't tested it with other mountable mobs, however.

**Comment by katubug** [comment]
Oh, where are my manners. Here's a list of diagnostic information about my client configuration:

Minecraft version: 1.12.2
Forge version: forge-1.12.2-14.23.5.2846-universal
Modpack version (links to current modlist): [1.7.0](http://enthusiasticraft.cf/modpack-update-1-7-0/#modlist)
Mod versions: iceandfire-1.8.1, llibrary-1.7.19-1.12.2

Please let me know if there is any other information I can provide. Thanks!

**Comment by AlexModGuy** [comment]
You need the https://www.curseforge.com/minecraft/mc-mods/gotta-go-fast gotta go fast mod

**Comment by katubug** [comment]
@Alex-the-666 - I'm afraid that hasn't fixed the issue for us. We have the mod installed but we still get the "moved wrongly" spam and my players still bug out.

I am using: `gottagofast-1.1.jar` which is the latest.

FWIW we have flight enabled in our server.properties and do not experience this issue with flying/teleporting players. Additionally, this issue did not exist in previous versions of Ice and Fire, so I have to conclude that there was something in the most recent update that may be responsible. Please let me know if there's any other information I can give you! :)

**Comment by AlexModGuy** [comment]
did you encounter the error on 1.8.0? or on 1.7.1?

**Comment by katubug** [comment]
I've for certain encountered it in 1.8.1. I'm about to run a test instance with 1.8.0, I'll get back to you!

**Comment by katubug** [comment]
Hmm, okay, my results are a bit weird:

 With 1.7.1, I got a lot of `[14:25:33] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Amphithere (vehicle of Katubug) moved too quickly!` 
but few `[14:25:21] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Amphithere moved wrongly!` It seemed that the "moved wrongly" was usually right after mounting, while getting into the air, and the "moved too quickly" was during the course of the flight.

With 1.8.0, it was pretty much the same as 1.7.1.

With 1.8.1, there were a few "moved too quickly" errors, but they were overwhelmingly "moved wrongly" errors. Additionally, this was the first time I noticed some rubberbanding issues with the Amphithere's model beneath me.

The LLibrary versions used were 1.17.18 with 1.7.1, and 1.17.19 with 1.8.0 and 1.8.1. I did tests both with and without GottaGoFast but did not see any difference (but that could be because these tests were in singleplayer - I don't have a way to test them in a dedicated server environment, unfortunately).

All tests were done in a limited modlist with just a few other things I was testing (I can provide a list if wanted), and new worlds were created each time. Each time I spawned a new Amphithere, tamed it, and rode it around for a while.

**Comment by katubug** [comment]
Just an update on the server situation. After the most recent restart, I had one of my players try riding her amphithere again, and it seemed to work okay. Here's the console log: https://pastebin.com/1pJScrVS

There were a couple of errors, but nowhere near the spam that we received previously. And the desync didn't happen. So I guess the reason it wasn't having an effect in singleplayer was because it was server-sided only.

On the other hand, shortly after our test, the amphithere spazzed out and suffocated itself in a wall, so that sucked. xD Probably not related, though.

**Comment by AlexModGuy** [comment]
yeah it turns out im going to have to do some coremodding to fix this issue, but that will have to come in a later update. either that or make dragons some sort of godlike entity that is unrestrained by vanilla(i need time to research this)

**Comment by katubug** [comment]
Understandable. Thank you for your help! We appreciate it. :)

**Comment by AlexModGuy** [comment]
alright, new build will be rolling out this week. included is a coremod(you dont need to install anything extra, it just means I did some hacky code so i can edit vanilla side stuff) that disables both the "moved wrongly" and "moved too fast" messages along with the teleporting that they cause. Atleast while riding a dragon, amphithere or hippogryph.

**Comment by katubug** [comment]
Ah, cool, ty!
