### ISSUE TITLE
No loot inside chests at dragon nests or lairs

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#1845]
After updating Ice and Fire to 1.8.1 and starting a new world, all the chests inside underground dragon lairs or at a dragon nests are empty, making the gold or silver nuggets the only obtainable loot. Previously using 1.7.1 there was always several types of loot inside these chests.

Details:
Minecraft 1.12.2
Forge 2844
Ice and Fire 1.8.1

I can also provide a full modlist if necessary. Let me know if there is any other information I can provide.

**Comment by maciek204290** [comment]
Can confirm, the update seems to have broken loot generation, though not entirely: some lairs still have loot, but most do not.

**Comment by katubug** [comment]
I think I may be experiencing something similar. The chests primarily just have gold nuggets and chain links with occasional pieces of gear or diamonds. I haven't come across any completely empty ones, but sometimes there will be a double-chest with nothing but 2 gold nuggets in it.

However, what really stands out is that with the underground caves, there is loot *all over the floor.* Diamonds, Enchanted Books and Armor, unenchanted Armor - all the things I'd expect to be in the chests are just floating as items on the ground. It's kind of a neat effect, but I'm a little worried about what it could do to my server environment, lagwise.

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.1](http://enthusiasticraft.cf/modpack-update-1-7-1/#modlist)
* **Mod versions:** iceandfire-1.8.1, llibrary-1.7.19-1.12.2

Hopefully we can get this sorted soon, let me know if I can help out in any way! :)

**Comment by AlexModGuy** [comment]
odd, not able to replicate. @katubug 1.7.1 has a kinda crappy loottable for the chests so its no suprise that you only have a few nuggets and diamonds, and the chestbreaking is most likely from a dragon breaking the chest and nocking its content everywhere.

**Comment by katubug** [comment]
Ah, sorry, the 1.7.1 is actually the version of my modpack, I was using version 1.8.1 of the mod.

I also have dragon griefing set to false - would it still be possible for them to have broken all those chests?

Edit: Also, I'll test this out again tomorrow in a new world and see if it's still happening.

**Comment by katubug** [comment]
I created a new world with Ice and Fire 1.8.2 and went into the Twilight Forest (my pack has them disabled in the overworld) to fly around in Spectator mode.

Here's an album of screenshots: https://imgur.com/a/nbV12Xe

All the dragons should have remained sleeping, presumably, since I was in spectator/creative the whole time. Dragon Griefing is also set to false. I cleared all the dragons via command so I could see the floor better, but not all items were near where the dragons were sleeping. Nothing else appeared to be disturbed.

Anyway, it's not a huge issue but I figured I'd report it! Thank you for your time. :)

**Comment by katubug** [comment]
Sorry, one more update. I was testing something else and happened upon a dragon's nest in the DeepDark. This time it is visibly clear that the items on the ground were not near the sleeping dragon:

![2019-10-07_18 32 31](https://user-images.githubusercontent.com/20935286/66356560-0189fb00-e931-11e9-849e-2eaff2b8e18b.png)
![2019-10-07_18 32 33](https://user-images.githubusercontent.com/20935286/66356561-0189fb00-e931-11e9-86be-aa7c7744a30d.png)

Thanks again!

**Comment by Mekadrom** [comment]
I have noticed this problem on a server I've been playing on that has this mod in its modpack. I have found around 4 untouched dragon nests (3 undergound, 1 roost), and none of them had loot in the chests. I don't think this is because somebody else got to them first because:

- The dragons were all still alive
- Gold piles were still there
- Chests that were in positions where they couldn't be opened without removing a block on top of them were also empty (what are the chances someone breaks the block on top, loots it, then replaces  the block?)
- No avenues of entry into any of them other than the roost
- Not even garbage loot is left - who takes absolutely all of the loot?

So, I think the loot generation is kind of broken at this point. I have found one dragon lair that had no dragon and was obviously ransacked, but there was still some loot in the chests. This lair was the only one in the overworld that I found, so maybe there is a problem with the dimensions? These were all in the twilight forest.

**Comment by ghost** [comment]
I'd like to note that restarting a world using Ice and Fire 1.8.2 (and since updated to 1.8.3) I've raided several dragon lairs (both above and below ground) and there has been loot in all of them.

**Comment by Mekadrom** [comment]
How can I tell what version the server I'm on is running?

**Comment by ghost** [comment]
@katubug maybe you could try adding chests to the blacklist of items that dragons are able to burn/break? I did that in my pack and it has prevented a lot of loot from getting dropped on the ground and eventually despawning.

@Mekadrom you can check the file in your mod folder or view the version from the Mod Options screen in-game.

**Comment by XarenHypr** [comment]
I have come across this issue as well after I updated to 1.76a from 1.58 a few days ago (long hiatus, RL reason).  I loaded up my existing world and went exploring to see some of the changes, however both in areas I had already loaded, and in chunks I generated afterwards for a test, none of the dragon lairs (surface and underground) had any loot in their chests.  The chests were not broken, and the silver/gold piles were still present as well, all of the chests were just empty.  Would a revert to an earlier version perhaps fix this (not intending to start over, as I had just begun my space preparations)?

Minecraft version: 1.12.2
Forge version: 2847
Modpack version: 1.76a
Mod versions: iceandfire-1.8.3
