### ISSUE TITLE
Frozen effect blacklist

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#1862]
A list of mobs from mods that should be immune to the ice dragons freezing effect as they are made from ice:
Vanilla MC: Snowman, Stray
Ars magica 2: Winter Guardian
Twilight Forest: all mobs in the ice biomes like the yetis, wolves, ice cores and the ice queen
Lycanites mobs: Every artic mobs
Mowzies mobs: Frostmaw
Normal animals like polar bears and penguins arent mentioned, as they are mortal beings and cant stand the extreme freezing

**Comment by BugmanBugman** [comment]
this isn’t an issue either plz put in suggestions

**Comment by SonicX8000** [comment]
Would this include the Frozen Effect from the Blizzard Modifier/Trait if you have Tinker's Construct? There's a few mobs that I would add into the blacklist since it could cause a few things to occur...

Twilight Forest's Phantoms... they pass through blocks and if you freeze them... they fall out of the world.

Betweenlands' Primordial Malevolence Boss... as you can shatter one of it's shields and then endlessly freeze it so it never can attack you.

Aether Legacy's Sun Spirit... well... haven't tried using the Freeze Effect on this boss yet but... seems odd that you can freeze it if it works on him.

A configurable blacklist could work where if the mob is added into the list it'll become immune to freezing.
