### ISSUE TITLE
Particles still disappearing on client when not in dev environment

### ISSUE THREAD

**Issue by AlexModGuy** [Alex-the-666/Ice_and_Fire#1892]
Particles never cause memory leak/stop spawning in dev enviornment, but do on the clients. My suspicion: Optifine.

**Comment by ColaLiao** [comment]
But we are not use Optifine...

**Comment by ghost** [comment]
Sorry for my bad english.
I think maybe you should check **this.world.isRemote** before spawn particles, because when I tried to debug your mod in release environment(sounds weird), I found the **IceAndFire.PROXY.spawnParticle** method was called on both client and server threads (in singleplayer mode).
![20191026211041](https://user-images.githubusercontent.com/20377926/67620296-e9264580-f837-11e9-96c3-3b15664652a5.png)
Minecraft's particle system uses ArrayDeque to process the spawn request and it's not thread-safe, so I guess the question is the spawnParticle method called on the Server Thread lets the Client Thread doing a dirt read and finally destroy particle system's request queue.
