### ISSUE TITLE
Missing Entity causing server memory overloads on a RL CRAFT pack server

### ISSUE THREAD

**Issue by GeorgeWL** [Alex-the-666/Ice_and_Fire#1998]
It may not actually be your mod, but some interactions going weird, but reporting it just in case.

This has only started happening in the last few weeks.

On our RLCraft server we keep getting crippling memory overloads.

everytime when the memory usage overloads this message appears

```bash
[15:48:54] [Server thread/WARN] [Sponge]: No entity type is registered for class com.github.alexthe666.iceandfire.entity.EntityDragonPart
```

**Comment by Xorbah** [comment]
Want to know why you're getting memory overloads? It's mostly in part due
to the fact that modpacks that large are nearly unsustainable and will
inevitably break itself if you give it enough time. Various errors ranging
from mods not functioning properly due to other mods implementation of
things conflicting with it, graphical errors, worldgen issues, the list
goes on. RLCraft is an absolute dumpster fire and packs that large are just
too ambitious as unstable as modded Minecraft tends to be. It may or may
not be IF doing this but usually what I said above is what the culprit ends
up being.

**Comment by GeorgeWL** [comment]
I will say, it only began happening around about Halloween, so I feel like it could be caused by a timed Halloween event.

**Comment by AlexModGuy** [comment]
dupe #1993

**Comment by GeorgeWL** [comment]
@Xorbah not useful.

**Comment by BugmanBugman** [comment]
> @Xorbah not useful.

you’re 3 months too late. RLCraft uses an outdated version of ice and fire.

**Comment by GeorgeWL** [comment]
just stating that coming into a issue tracker and saying "the way it's being used I disagree with" is useless, and entirely off-topic.

It's an issue tracker, not a pointless opinions tracker.
