### ISSUE TITLE
Ice and Fire Mobs not respecting their mob stage

### ISSUE THREAD

**Issue by Winddbourne** [Alex-the-666/Ice_and_Fire#2022]
I just got killed in a test game by a Stymphalion bird . . . the only problem is these birds are set in mob stages to only spawn near players with the stage "epic" which my character didn't have.  

The bird didn't care it shot my character to shreds . . . my character who only had five hearts, no armor, no tools, and no weapons.  It was completely crazy.  Last test game it was a cockatrice who instantly killed me . . . he shouldn't have been able to spawn either. 

This problem is so bad that until a fix exists I'll have to disable the hostile creatures entirely even though they are completely amazing.  The models are superb, their attacks well done, and I can set their health to obscene levels that would challenge players with fifty hearts and super tools. 

That is they are amazing IF they spawn when I say the player is ready to encounter them . . . but if they go rogue and spawn before I tell them it's OK then they are completely game-breaking.  Very few players are going to call it fun, or balanced if they get killed in one or two hits while looking around for the unkillable monster that is firing at them from a distance.

**Comment by AlexModGuy** [comment]
dupe #2105

**Comment by Dread131313** [comment]
So because the mod author doesn't seem to give two rats asses about this problem, i have a solution. use the mod InControl and use an "onjoin": true, argument and make these fucking mobs spawn with like -99% health and damage.

Sirens are ok I guess because you can just earplug them, but it forces you to forego your helm or fight them.. whatever.

But the other mobs, like sea serpent, stym bird, hell even griffons i think are just flat out fucking refusing to obey game stages rule. using InControl for applying stages to these mobs as well as using the mod MobStages is worthless and doesnt work. This mod and a handful of other mods are the only ones that have this issue. This leads me to believe that the mod authors are circumventing the usual spawn checking method present in vanilla and are using some other retarded means of spawning.
It doesn't make sense but if the mod author is gonna refuse to fix this, let alone give a respectable and competent reply then InControl is the way to go or disabling the entire mod or mobs altogether.

It sucks, it really sucks but it is what it is I guess.
