### ISSUE TITLE
Game Stages Integration

### ISSUE THREAD

**Issue by CalaMariGold** [Alex-the-666/Ice_and_Fire#2105]
It would be amazing if we can lock dragon spawns behind a Game Stage.

I'm not sure how this would work with the structures the dragons spawn with, but at least spawning the dragons themselves with Game Stages would be fine.

Thank you!

**Comment by CalaMariGold** [comment]
Another idea I got. Spawn the structures no matter what, but once the stage is unlocked, dragons will then spawn at the structures.

Or, dragons and structures spawn no matter what, but dragons are invincible and sleeping until the game stage is unlocked.

**Comment by CalaMariGold** [comment]
I really really need this for my modpack, because at the moment, skilled players can completely skip over half the game by obtaining OP armor on day 3 from cheesing a dragon kill.

**Comment by democat3457** [comment]
;-;

**Comment by Dread131313** [comment]
So you didnt fix or address this issue? You just closed this one and the other issue that was like this one? Im looking at the changelog for this all the way to the latest 1.12 and I dont see any mention of gamestage integration working. Hell, even incontrol doesnt work. Either the mobs spawn or they dont. They spawn whenever they want to unless disabled. Like for instance ive got sirens locked behind stage 2 supposedly and yet I just got pulled by one of their songs and im still in stage zero. This is annoying because I love this mod but having these mobs spawn during an early game stage pack is kinda of a pain because they are tough early game.
