### ISSUE TITLE
Suggestion: AM2/Magic Damage in general 

### ISSUE THREAD

**Issue by LatentDesire** [Alex-the-666/Ice_and_Fire#212]
Was watching videos on YouTube. Saw a max level fire dragon get 2 shoted by a high level ice spell from Ars Magica 2. I believe it was blizzard. I'm not certain if was due to it being ice damage, or magic damage in general, but I feel that dragons should be resistant to magic. (Baring blood alchemy from the mod.)

The video can be found here. The part in question starts around the 20 minute mark. (And he's invisible, though he did report similar AI behavior in a test world while visable.)

https://youtu.be/U8kTep3Dlxg

There is a younger dragon who is similarly done in with a standard ice spell earlier in the same video.

**Comment by EnderiumSmith** [comment]
some regular armor points could also be added. zombies even have 2(8%). 
defense vs magic equals to that of a witch might be a good value. 
maybe even some magical defense against any damage.
it should be checked that the damage source does not ignores magic before reducing it. for both cases. magic damage that ignores magic defense would not make much sense, but that is o be decided by the one who does it, not who recieves it.

**Comment by LatentDesire** [comment]
I'd like to know what the max magic defense is possible for armors with Ars Magica 2 installed, and the magical damage defense infusion on it. Dragons should always be a challenge to battle, even for powerful mages.

**Comment by KingBishop3** [comment]
I saw nothing particularly amiss with the video. I am not sure if you have ever played with Ars Magica, but there are "silver" spells... spells you have to unlock by crafting certain other spells. Blizzard is one of those... and not a well documented one at that. He even mentions in the video that he had to decompile the jar file in order to get the particular unlock combination. It took 7-8 hits from a normal ice spell to kill that stage 3 dragon in the air (not unreasonable imo for a magician likely north of level 100 based on apparent mana costs).

**Comment by Alex-the-666** [comment]
Move this to the suggestion tracker https://github.com/Alex-the-666/Ice_and_Fire_Suggestions/issues

**Comment by Alex-the-666** [comment]
broken link https://github.com/Alex-the-666/Ice-and-Fire-Suggestions/issues
