### ISSUE TITLE
Dragons keep waking up

### ISSUE THREAD

**Issue by Druiddraws** [Alex-the-666/Ice_and_Fire#2234]
this has been happening in every new world i make and its been bothering me quite a lot. i know sometimes dragons will just wake up ever so often, but this is every cave i've ever gone over, every single dragon that lives in a cave has woken up and will come out and either crash the game or destroy everything, it makes it impossible to play. its really sad because ice and fire has always been my #1 favorite mod ever since i found it :(

**Comment by DonTheBreton** [comment]
I have this same issue in multiplayer.

Version: 1.8.4-1.12.2

My investigations have discovered that this is actually because in previous versions, the dragons would try to burrow up, but get easily stuck on blocks and stay underground. The most recent update made them not as likely to get stuck on blocks underground and now they burrow through everything.

My understanding is the intended behavior is that they should remain sleeping until someone enters their chamber or at least within a few blocks of the dragon without sneaking. However, these dragons are burrowing up just to chase nearby animals.

Identical Issues: https://github.com/Alex-the-666/Ice_and_Fire/issues/2228 https://github.com/Alex-the-666/Ice_and_Fire/issues/2239
