### ISSUE TITLE
underground dragons wake up instantly

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2235]
wild dragons underground wake up from their dens and attack when I walk on the surface.

**Comment by DonTheBreton** [comment]
I have this same issue in multiplayer.

Version: 1.8.4-1.12.2

My investigations have discovered that this is actually because in previous versions, the dragons would try to burrow up, but get easily stuck on blocks and stay underground. The most recent update made them not as likely to get stuck on blocks underground and now they burrow through everything.

My understanding is the intended behavior is that they should remain sleeping until someone enters their chamber or at least within a few blocks of the dragon without sneaking. However, these dragons are burrowing up just to chase nearby animals.

https://github.com/Alex-the-666/Ice_and_Fire/issues/2228 https://github.com/Alex-the-666/Ice_and_Fire/issues/2239 https://github.com/Alex-the-666/Ice_and_Fire/issues/2234

**Comment by AlexModGuy** [comment]
fixed
