### ISSUE TITLE
Stage 4 & 5 Dragons never stay underground

### ISSUE THREAD

**Issue by bugSandwich** [Alex-the-666/Ice_and_Fire#2239]
Stage 4 and 5 dragons will often dig themselves up from their caverns to attack players even when they are quite far up above them on the ground. They also seem to be able to detect your position through the dirt (even with dozens of blocks of stone and dirt blocking them), since they dig themselves up if you dig beneath them and will follow you above ground until you surface. Dragons also seem to emerge from the ground even when there is no cavern, or at least the tunnels they leave behind scarcely lead to a cavern in my experience. Dragons also seem far too aggressive to players since they will, even quite a distance away, abandon attacking all other mobs and attack the player exclusively (although, perhaps this was intentional)

**Comment by DonTheBreton** [comment]
I have this same issue in multiplayer.

Version: 1.8.4-1.12.2
 
My investigations have discovered that this is actually because in previous versions, the dragons would try to burrow up, but get easily stuck on blocks and stay underground. The most recent update made them not as likely to get stuck on blocks underground and now they burrow through everything.

My understanding is the intended behavior is that they should remain sleeping until someone enters their chamber or at least within a few blocks of the dragon without sneaking. However, these dragons are burrowing up just to chase nearby animals.
