### ISSUE TITLE
Ice Dragon Egg despawns after placement with Sponge.

### ISSUE THREAD

**Issue by JoelKovalcson** [Alex-the-666/Ice_and_Fire#2259]
As per the title, we've had a lot of issues with Ice Dragon eggs despawning after placement (after a short period of time). Sometimes the water freezes like it's supposed to, but the egg still despawns. 

Modpack: Enigmatica 2: Expert Mode v1.77
Sponge Version: 1.12.2-2838-7.1.7

Not sure if this issue is with Sponge or Ice and Fire, as no config alterations have changed this issue on the server I've been testing with.

**Comment by Danyerious** [comment]
I believe it's Sponge's problem. Because I think Ice and Fire more likely fits with Forge instead of Sponge.

**Comment by JoelKovalcson** [comment]
I fear as much, though trying to get support for a single mod is...Iffy at best from something like Sponge or Enigmatica. I suppose I shall see what happens.

**Comment by Danyerious** [comment]
Agreed. Sent from Mail for Windows 10 From: Joel KovalcsonSent: Thursday, April 2, 2020 7:39 PMTo: Alex-the-666/Ice_and_FireCc: Danyerious; CommentSubject: Re: [Alex-the-666/Ice_and_Fire] Ice Dragon Egg despawns after placement with Sponge. (#2259) I fear as much, though trying to get support for a single mod is...Iffy at best from something like Sponge or Enigmatica. I suppose I shall see what happens.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Danyerious** [comment]
Agreed.
