### ISSUE TITLE
Dragon Experience Level Drop less than Ender Dragon

### ISSUE THREAD

**Issue by SteveAdture** [Alex-the-666/Ice_and_Fire#2271]
after everyone kill Ender Dragon It will give 68 xp levels
but Fire/Ice Dragon(Stage 5) also drop 9 xp levels even though they have more health and harder to kill than Ender Dragon
![dragon](https://user-images.githubusercontent.com/53965412/78536608-5511ce80-7818-11ea-8667-34bec98fabb0.png)

**Comment by bugSandwich** [comment]
The ender dragon is fairly difficult to kill multiple times, whereas dragons are far more plentiful. The XP difference might be to prevent an advanced player from easily farming experience from just killing a large number of dragons, probably with their own dragon. Also, I&F dragons drop highly valuable loot compared to the ender dragon, so that might also explain the disparity.

**Comment by Breadstickpotato** [comment]
Dude that thing is **MASSIVE!**
