### ISSUE TITLE
Stone Mobs Remaining after hit

### ISSUE THREAD

**Issue by GalacticTaillow** [Alex-the-666/Ice_and_Fire#2398]
in Version 1.9.1, Mobs frozen by Gorgons will remain once they're hit with a pickaxe, the stone models vanish yet the entity remains and no drops come of it? I believe this will have the possibility to cause rendering issues if too many entities are loaded in like this?
![Capture](https://user-images.githubusercontent.com/64514399/80559524-5eb7cd80-89a3-11ea-9d87-22079467147b.PNG)

**Comment by fkshitanoiyingcrap** [comment]
Can confirm this is an issue, trolls entity or whatever the fuck does not dissappear after killing and mined with a pickaxe.

I know for sure because i have the mod "Open Modular Turrets" and the turrets still shoot at the spot where the troll died even after i mine it.

Sometimes the stupid trolls weapon also remains in the air after I mine the dead troll

**Comment by Hamsterbutt** [comment]
Same issue with trolls, have to keep whacking the invisible space/entity with a pickaxe until it drops stone and "dies" and the weapon disappears

**Comment by darchitectlp** [comment]
I'm seeing this, as well. It's particularly problematic with the trolls and turrets. Also using 1.9.1.

**Comment by TheK0tYaRa** [comment]
Recreated on 1.9.1 mod after searching why Cave Troll wasn't minable with ultimate pickaxe from Mekanism (atomic disassembler). It seems that it's intended to have a cracked texture but is missing it.
