### ISSUE TITLE
Dragon stuck on shoulder

### ISSUE THREAD

**Issue by Manticat** [Alex-the-666/Ice_and_Fire#2402]
Whenever I hatch a dragon then right click it to put it on my shoulder it doesn’t actually get off. When I shift to get it off, it teleports to where I picked it up but it doesn’t move and acts like it’s still there on my shoulder.

**Comment by JenisisJo32** [comment]
Looks like this is a glitch with 1.9.1, a few other people have made posts with the same issue you and I are having with the little stage 1's. I tried picking up my fourth hatchling after putting down the other three, and the fourth just vanished. May have to roll back to 1.9.0 until a bugfix comes out, or just not move your hatchlings, as picking them up through other means (golden lasso, dragon horn) seems to also be causing severe issues.
Edit: Found the fourth, turns out ice dragons are really, really fast swimmers when they're young. Spent a good ten minutes chasing her.

**Comment by Manticat** [comment]
Hm, alright. Thanks for the tips!
So, this bug is just in 1.9.1?

**Comment by JenisisJo32** [comment]
Just 1.9.1, yup. I just downgraded to 1.9.0, and while there is a small amount of rubberbanding, the hatchling only went a few blocks away, instead of hundreds.

**Comment by Manticat** [comment]
Alright, thank you for the help!

**Comment by AlexModGuy** [comment]
fixed
