### ISSUE TITLE
Baby dragons won't move

### ISSUE THREAD

**Issue by Amayapuppy** [Alex-the-666/Ice_and_Fire#2405]
Stage 1 dragons can't be carried away from where they're hatched. When picked up they go onto your shoulder but as soon as you put them down they teleport back to their hatching spot. Forcefully moving a dragon (Via golden lasso from extra utilities 2) causes the dragon to "remain" on your shoulder invisibly however it still makes sounds.
Somehow killed an invisible baby dragon by being near it while without hitting it and said dragon was also on another players shoulder (despite them saying they sat it down).

**Comment by xMrCaosx** [comment]
I hv the same problem.

**Comment by angel124xxx** [comment]
Same here ^

**Comment by AlexModGuy** [comment]
fixed

**Comment by jazzhar** [comment]
I am on the latest version but this exact issue seems to happen again. My Lil dragon apparently got himself drowned while visually not having moved at all. I made sure it wasn't set on staying. 

it fixes itself after some time causing the dragon to wander again, but when shouldered and unshouldered it simply teleports to a new spot a few blocks away from the old. causing it to be unable to wander again.

using a horn makes the dragon able to wander again, but picking it up and setting it down teleports it to the position it was picked up on.

 I hope this gets fixed again soon since its just so adorable on my shoulders xD
