### ISSUE TITLE
Death worm causing extreme lag

### ISSUE THREAD

**Issue by vani2620** [Alex-the-666/Ice_and_Fire#2428]
I'm playing on a custom modpack with Ice & Fire in it, and according to LagGoggles, a death worm near spawn was adding 1.6 seconds per tick.

Version: 1.9.1

**Comment by Baloob** [comment]
I got the same problem too on Version 1.12.2 and created with a own created modpack. The Server lags if any deathworm is near.
And u cant get to the desert because the server is crashing. I opened the config of Ice and Fire and changed the spawn rate from 2 to 1, the spawn check to 10 and the death worm attack range from 64 to 10. I didnt test it yet but it needs to work definitely better yet.

**Comment by Baloob** [comment]
> I got the same problem too on Version 1.12.2 and started a Server with a own created modpack. The Server lags if any deathworm is near.
> And u cant get to the desert because the server is crashing. I opened the config of Ice and Fire and changed the spawn rate from 2 to 1, the spawn check to 10 and the death worm attack range from 64 to 10. I didnt test it yet but it needs to work definitely better yet.
