### ISSUE TITLE
Entity selectors for server owners?

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#2430]
I've spent hours searching on the internet for this, and I cannot find the entity selectors for /kill for any of your mobs. I'm running a server, and it's miserable going out and having to deal thousands of damage to one of these things when they're terrorizing one of my players.
Is there any chance that the wiki / repository could be updated with a list of the entities that this mod registers?

**Comment by Skydragonsz** [comment]
if you have WAILA installed or TOP it shows the ID of the entity. 
Two examples 
![image](https://user-images.githubusercontent.com/1357800/81380759-b248ba80-910b-11ea-8769-378273c88431.png)
![image](https://user-images.githubusercontent.com/1357800/81380785-bb398c00-910b-11ea-9899-c3f127e6432f.png)

So in my case: /kill @ e[type=iceandfire:icedragon,r=25] 
without the space (cus I by accident tag someone)
the r (radius) because I don't want to kill every dragon
