### ISSUE TITLE
ice/fire dragons and structure spawns not obeying blacklist

### ISSUE THREAD

**Issue by Wrsaith** [Alex-the-666/Ice_and_Fire#2466]
so I've setup a server on 1.12.2 minecraft, and in the config for ice/fire I've blacklisted the overworld for spawning of any kind from ice/fire but dragons and all other ice/fire structures and creatures are still spawning.

in addition the structure spawns are spawning 3 to 15 blocks above/below the actually terrain and I've seen entire structures sunk in the ground till the roof was level with the ground around it.

are other mods capable of overriding Ice/fires configs and still forcing spawns?

iceandfire 1.9.1-1.12.2
MC 1.12.2

**Comment by a404error** [comment]
I think I've got the same or similar issue as well (1.12.2). I basically have the "use dimension blacklist" set to false so that instead, the game pulls from the whitelist. In my whitelist, I have listed dimension 111 (The Lost Cities) only. I still get spawns of Ice and Fire mobs in the overworld though. Based on the description in the config, it appears the black/white list might only affect the dragon mobs and not all the other mobs Ice and Fire adds, which seems rather odd.

As a workaround, I've tried to use the custom spawning from Endor IO Zoo by adding Ice and Fire mobs to the dimension exclude list, however either I'm not using the correct modid:mobname or that config is being loaded before the Ice and Fire config as Ice and Fire mobs are still spawning in my overworld.
