### ISSUE TITLE
Dread queen blade bug in I/F version 1.9.1

### ISSUE THREAD

**Issue by JosephGallagher2001** [Alex-the-666/Ice_and_Fire#2545]
Hey, so I noticed that the Dread queen blade accepts enchants such as mending and unbreaking, yet they do nothing to repair the blade using XP when it gets damaged, in the case of mending, and unbreaking does nothing to reduce the overall durability loss that comes with using the sword and having it get damaged. Perhaps this is just a bug, as my issue title suggests, but it might also be an intentional part of the mod. If this is a bug, I hope that it will get fixed in version 2.0.0 of the mod, but if it is intentional, please tell me.

**Comment by QuantumExp** [comment]
It's possible that this is a bug, but considering the item in question can only be obtained via Creative, JEI, and/or cheats, and the fact that the Dread Queen is not in this update, it's possible (not probable) that this is intended. If this is a bug (which I sincerely doubt it isn't one), hopefully this will be fixed in either 1.9.2 of the mod or 2.0. Whichever comes first.

**Comment by JosephGallagher2001** [comment]
ok, thanks for the help.
