### ISSUE TITLE
龙吟号角召唤蹦端

### ISSUE THREAD

**Issue by YeiShen** [Alex-the-666/Ice_and_Fire#2637]
> 
![J)@2I~74F{IA W1NS`0 `KJ](https://user-images.githubusercontent.com/52132450/91524420-c1a97900-e931-11ea-9331-f5bcf2699433.png)
在服务器里使用龙吟号角召唤就秒蹦了后台出现了报错

**Comment by RisingInIris2017** [comment]
## Versions
#### Mod version:
iceandfire-1.9.1-1.12.2

#### Forge version:

14.23.5.2854

#### Singleplayer or Multiplayer:

Singleplayer, on Integrated singleplayer server.

#### Installed mods:
You may see the full mod list in the crash log attached below.

## Link to full crash log

https://paste.ubuntu.com/p/6QKT6CBBpW/

## Description of the problem
#### How to reproduce:
1. Use a Dragon Horn to catch your dragon.
2. Right click with this horn in your main hand.
3. Game crashes.

## Additional information
I have the same issue with this issue's poster. Though he has not described his issue in English, I think he does not intend to be offensive, but is just not so good in English. However, this issue is existing indeed. So I post this issue here.
Hope to get your help, and it is highly appreciated.
Thanks in advance!
