### ISSUE TITLE
underspawning/exceedingly rare den generation if biome mods present

### ISSUE THREAD

**Issue by kuroyure** [Alex-the-666/Ice_and_Fire#2710]
whenever ice and fire is installed alongside a biome mod that has a biome that should spawn a dragon (i.e with the jungle or snowy type) its nigh impossible to find the mod's structures and creatures hippocamppi are too rare, and therefore i never saw one being killed by a sea serpent

**Comment by Quatronomikon** [comment]
Same problem...

**Comment by SLZT** [comment]
Well ice and fire isn't really compatible with biome mods. The specific dragon types only spawn in their designated bioms such as ice bioms and sand bioms, if you ask why he doesn't just make them spawn in any biom it's because of the dragon type. Fire dragons would spawn in ice bioms ans ice dragons in sand bioms when the owner would make dragons spawn in all bioms. So the only thing the owner could so is support specific bioms mods which is unlikely he will do that tho.
