### ISSUE TITLE
Arrows doesn't work whit any bow.

### ISSUE THREAD

**Issue by kjwweehd1** [Alex-the-666/Ice_and_Fire#2712]
Arrows doesn't work except normal minecraft arrows. It has shooting animation and decrease number of arrows, but when i release it nothing.

**Comment by SLZT** [comment]
Do you have any mods except ice and fire? If yes try removing them except ice and fire and caditel, then adding them back one by one to find the mod that brings the issue. If you don't have any other mods except ice and fire and caditel then try deleting ice and fire and caditel, redownload the newest versions (From curseforge) and generate a new world. If it still doesn't work then I'm not sure why this bug is happening. I can use the arrows normally.

**Comment by kjwweehd1** [comment]
Thanks for replying. NotEnoughEnchantments+V0.0.3 is the problem.
