### ISSUE TITLE
Cascading worldgen

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Ice_and_Fire#284]
[02:34:35] [Server thread/WARN]: Ice and Fire loaded a new chunk (-2, 27  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Encountered on 1.11.2. Might want to look into it.

**Comment by AlexModGuy** [comment]
hmmmmm

**Comment by AlexModGuy** [comment]
"Cascading worldgen is when the following happens:

    a chunk is generated, which has a structure in it

    the structure is large and crosses a chunk boundary

    the adjacent chunk is generated in order to complete the structure

    the adjacent chunk has another large structure in it

    repeat ad infinitum

The way to resolve it is to have fewer and/or smaller structures. Start by curtailing those with less gameplay value. Quark's marble/limestone/etc. is a particular culprit for cascading worldgen. Marble is redudant with Astral Sorcery, so turn off Quark's marble and tone down the other stones."

Disable structures if you dont want this because there is no work around apparently
