### ISSUE TITLE
Dragon Roost generation ignores dangeous world gen distance config value

### ISSUE THREAD

**Issue by chupybara** [Alex-the-666/Ice_and_Fire#2858]
Dragon roosts do not appear to be respecting the config value for dangerous world gen distance from other dangerous structures.  In a few tests, I had instances where the above-ground dragon roosts generated within 300 blocks of each other, while the distance was set to 1000 in the config fiel.

**Comment by Sheld42** [comment]
Got pretty same bug. I decreased spawn chance of roosts so dragons really rare in my world, but if I found 1 of them there are like 2-4 other roosts and dragons nearby within even 200 or 50 blocks.
Are they supposed to live in dragons big famillies? :)

**Comment by Peach774** [comment]
Bumping this issue because I am also running into it. It seems like neither the dragon roost chance or the dangerous world gen config do anything. Here you can see 2 roosts within 300 blocks of each other, which I believe is the default distance: 
![image](https://user-images.githubusercontent.com/5171184/96359200-c9310700-10c4-11eb-9562-6bed9f8f7888.png)
