### ISSUE TITLE
Gorgon temple 

### ISSUE THREAD

**Issue by nickiminaj22** [Alex-the-666/Ice_and_Fire#2986]
When temples spawn in biomes with no sand, they extremely out of place because they come with sand as the foundation. Removing it and having it appear with the blocks that it’s around would allow them to look more natural and blend with the environment.

**Comment by Noahleon000** [comment]
+1 to this its pretty annoying when the temples just make a hole in the surrounding water and destroy the environment

**Comment by bessiq** [comment]
Wait until you see the new graveyard worldgen. 😬 

To be fair, this mod is awesome and is trying to do a lot of awesome things we probably aren't worthy of, so I'm willing to endure some extra weirdness until fixes happen because RAWR OMG DRAGON RUN. ❤️ (But yeah, those graveyards make the gorgon temples look normal af. lol.)
