### ISSUE TITLE
1.16.3 - New Banner Patterns Not Loading Texture

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Ice_and_Fire#3037]
Forge: 34.1.25
Mod Version: 2.1.0 - 1.16.3

Whenever I try to use a banner pattern added by Ice & Fire, it generates the missing texture instead. However, Immersive Engineering's banner patterns do work correctly.

**Comment by EigentlicherVogel** [comment]
Exactly the same issue occurring for 1.15.2 version of 2.1.0, forge version 31.2.45.

**Comment by BrokenValkyrie** [comment]
Minecraft 1.16.4 Forge 35.1.0 Mod version 2.1.3

Still having this issue, works fine with just the mod alone. Which meant it must be a mod incompatibility. After eliminating many mods I found the cause is oddly refined storage mod. However as TheQuantumRuby said immersive engineering banner still works fine even the culprit mod present.
