### ISSUE TITLE
Pixie House Render Crash

### ISSUE THREAD

**Issue by Vlogical123** [Alex-the-666/Ice_and_Fire#315]
Pixie houses seem to cause crashes upon trying to be rendered, however this just happened for the first time even after multiple other pixie houses have been rendered. The only relevant part, I believe, of the log reads out as follows (full crashlog pasted below): 

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.renderTileEntityAt(RenderPixieHouse.java:35)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.func_180535_a(RenderPixieHouse.java:17)

However, full crash log can be found here: https://pastebin.com/X2ARU9GC

Thanks,
Vlogical

**Comment by AnonRou** [comment]
I get the same exact error as well. Glad someone else also has seen it

**Comment by Rocco155** [comment]
I got the same crash and some observations. For me, it always crashes when a Pixie is leaving her house, and it might be related that my server crashes also when a Pixie is leaving a Jar in which I locked it up before and then destroy, in that moment my server also crashes. So I guess it has something to do with the Pixies coming out of something. 
[crash-2017-09-18_01.54.21-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1309568/crash-2017-09-18_01.54.21-server.txt)

(And it might be nice to have config to turn on or off if the Pixies can steal your stuff, because I would love to live in a nice BoP Cherry Blossom Grove close to a Pixie village, but I could not stand it to get my stuff stolen all the time and having to run after the thieves. Right now you have only the option to tame them all so they don't fly too far away with your stuff or let them sit down, because they can't steal when they are sitting. Or catch them all in Jars (and don't release them because of crashing))

**Comment by katubug** [comment]
I got a very similar crash while breaking a Pixie house to relocate it.

[crash-2018-01-03_14.56.31-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1601685/crash-2018-01-03_14.56.31-client.txt)

**Comment by brisingraerowing** [comment]
I've seen this with a number of other mods. Usually it's some mod not playing nicely with blockstates. Guarding against invalid blockstates seems to be how most other mods I've seen this kind of crash reported to fixed the issue (and that is probably a good idea anyways).

**Comment by AlexModGuy** [comment]
fixed
