### ISSUE TITLE
deadlock when generating new terrain

### ISSUE THREAD

**Issue by kuroyure** [Alex-the-666/Ice_and_Fire#3179]
whenever i try to generate new terrain with the 2 latest updates my game suffers with a deadlock issue and im incapable of interacting with the world, since there is no crash, ill post the log
https://pastebin.com/c2eaURLB

**Comment by 4TH315T** [comment]
this happens to me as well! Whatever I do, after a few loaded chunks the mobs freeze on the spot and interaction with the world is impossible.
No crashlog provided though since the game itself doesn't actually crash.

**Comment by Dyvinia** [comment]
I have the same issue, was able to figure it out by enabling forge debug: https://hasteb.in/zexuhuwa.md

**Comment by kuroyure** [comment]
can you guys provide modlists, since apparently other ppl are not having it, maybe its a mod interaction

**Comment by Dyvinia** [comment]
here is my modlist: https://hasteb.in/uxihalov.gradle

**Comment by 4TH315T** [comment]
here is the modpack I use (slightly adapted, but the full version won't make I&F work either)
https://www.curseforge.com/minecraft/modpacks/all-the-mods-6

**Comment by 4TH315T** [comment]
https://github.com/AllTheMods/ATM-6/issues/300#issue-741203913

tried this presumable recent fix, which didn't work either

**Comment by kuroyure** [comment]
its either quark or botania that are causing the issue if im not mistaken

**Comment by Carro1001** [comment]
I have tried this with just ice and fire/citadel and the internal server still froze

**Comment by kuroyure** [comment]
guess its waiting for alex then boys

**Comment by CosmicDreamsOfCode** [comment]
I think i narrowed the issue down to just the Ice Dragons in my testing without Botania. Same list as Dulana besides that. They believe it's the AI of the Ice Dragon locking things up.

**Comment by TacoSundae84** [comment]
I had a save that kept locking up the world and worldgen stopped a few chunks after an ice dragon roost (and 2 ice dragon caves right below it). I downgraded to the version from Nov 19th, and it fixed this problem, but i noticed right where the chunks stopped loading in the newest version, there's a mausoleum. 
I'm wondering if others could downgrade to the Nov 19th version and open up their worlds that are freezing to see if it works and generates a mausoleum nearby? It seems odd ice dragon ai is causing this but not fire dragon, especially since all 3 in mine were just sleeping. Dragon ai seems to be laggy in Nov 19th version, but doesn't completely lock up the server.

Edit: Now that the chunk the mausoleum were generated in the Nov 19th version, i went back to the current version, and it's working fine. Same spot with the dragon, and just some lag when it goes into the water, but not completely locking everything up.

**Comment by Carro1001** [comment]
The issue is mausoleums, i disabled them entirely by changing the config to this https://pastebin.com/v6hy7pxW and ive had no more freezes, even flew a good 2000 blocks

**Comment by D-Bigboy-302** [comment]
Ok I thought I was the only one experiencing this issue. Was driving me crazy, couldn't figure out what it was. This information was helpful. Hope it gets fixed soon, will just disable mausoleums for now
