### ISSUE TITLE
Dragon Shoulder Glitch

### ISSUE THREAD

**Issue by JustGreenz** [Alex-the-666/Ice_and_Fire#3205]
so I and my girlfriend are playing modded mc on our server and we have ice and fire installed we got some dragon eggs and for some reason, she can't see her dragon on her shoulder but on my screen, I can see it. I don't know why she can't see it. she can't place anything bc the dragon is on her shoulder but on her screen it's still on the ground is there any way anyone can fix this?
![unknown (4)](https://user-images.githubusercontent.com/66095112/100258381-059e2100-2f15-11eb-816b-3d9fe8e24854.png)
![unknown (3)](https://user-images.githubusercontent.com/66095112/100258387-0636b780-2f15-11eb-8baf-5b57eff3ac67.png)

**Comment by JustGreenz** [comment]
btw this is in 1.12.2

**Comment by Gisbert-Minecraft** [comment]
Hello,

And first of all - you made one of the best mods for Minecraft. Thank you!

I'm working on a private modpack and have done much testing with your mod even in multiplayer.
I have the same issue as JustGreenz.

Mod-Version: iceandfire-1.9.1-1.12.2
Mod-Loader: Forge 1.12.2 - 14.23.5.2854
The problem doesn't depends on other mods.

Once you picked up the Dragon, it stays on your shoulder even by pressing "X" or another configured button (tried).
Strangely you can 'unload' it with "shitft" (maybe from earlier versions?), but for everyone else on the server it's still displayed on the shoulder. When you do a relog, as soon as you logged out, the dragon immedietly appears for all players on the ground where you dropped it OR (in most cases) it teleports back to the place where you picked it up. I haven't figured out now in which case the drop of the dragon gets reseted. Maybe the game thinks, you never picked it up.

I know you don't support the 1.12.2 version anymore, but even if you don't fix it, can you offer a possibility or workaround to completly deactivate the shoulder feature? I Haven't found something in the config.

I regret asking this, because this feature is really a nice gimmik, but I still would prefere to disable this feature then have it bugged in the pack.

If you are interested, I can do some testings for you - for this issue or in general, I would offer my time and services. Because just now I left the main scripting phase and Me and my friends starting the testing procedure of the pack the next weeks. If you need additional information about that issue or something, just ask me.

I'm looking forward to hearing from you and keep up the good work!
