### ISSUE TITLE
[2.1.3] When a mausoleum attempts to spawn, floods log output with error messages and causes a hang up

### ISSUE THREAD

**Issue by AzaratheDragon** [Alex-the-666/Ice_and_Fire#3262]
Took a few trouble shoots and restarts to figure out what was happening, initially thinking it was a nearby ticking ice dragon (they've given me issues in older version of the mod), but after teleporting directly to the source using the output log's messages. It would appear the mausoleum (two actually in my case), had been attempting to spawn previous times and throwing continuous errors, causing the game to hang up. Couldn't even give a crash log if I wanted to, as the game doesn't crash. Just soft locks.

Output log looked like this though.
- [m[33m[16:05:15] [Worker-Main-13/WARN] [minecraft/WorldGenRegion]: Tried to access a block entity before it was created. BlockPos{x=526, y=64, z=12022}
- [m[33m[16:05:15] [Worker-Main-13/WARN] [minecraft/WorldGenRegion]: Tried to access a block entity before it was created. BlockPos{x=523, y=64, z=12018}
- [m[33m[16:05:15] [Worker-Main-13/WARN] [minecraft/WorldGenRegion]: Tried to access a block entity before it was created. BlockPos{x=523, y=64, z=12006}

The different coordinates are all within the confines of the structure, and my few jumps from one coordinate to the next pointed to it being the chests throughout the dungeon to be causing the errors.

Using Ice and Fire version 2.1.3 in Minecraft 1.16.3
Citadel version 1.5.3

**Comment by kirkleon** [comment]
Having (I believe) the same issue with Ice And Fire 2.1.4 and Citadel 1.5.3 on Minecraft 1.16.4. Server crashed with that same log spam any time some region got loaded, world also crashed in MCEdit. Brought it up in singleplayer and started disabling mods until I isolated that it was ice and fire behind it, and when I disable it and go to the offending region there's floating chests that say their loot has not been generated yet. 

I can provide more logs or a world save if it would be helpful, but I'm not sure how useful they are since I'm not seeing any errors about the actual structure generation.
