### ISSUE TITLE
Gorgon heads have infinite uses

### ISSUE THREAD

**Issue by BugmanBugman** [Alex-the-666/Ice_and_Fire#3322]

**Comment by JosephGallagher2001** [comment]
are you in creative or survival?

**Comment by JosephGallagher2001** [comment]
cuz creative mode gives infinite use on everything, but survival shouldn't...

**Comment by Lashriel** [comment]
I think most users are smart enough to realize creative mode does that and not make a github issue for it.

Can confirm, gorgon heads can have multiple uses (may be infinite, haven't had cause to use it more than once) in survival. Just killed a gorgon, petrified a wandering trader with the head because I got tired of hearing the "hmm-hmm" around my base, still have the gorgon head.
