### ISSUE TITLE
Bestiary/Lectern Doesn't Consume Manuscripts

### ISSUE THREAD

**Issue by grayscale420** [Alex-the-666/Ice_and_Fire#3324]
If you use the lectern to fill entries in the bestiary you can take the remaining manuscripts out, put them back in or exit and re-enter the lectern which returns the initial manuscripts. The lectern still fills out the book, so at least that's working properly.

Version: 2.1.4 - 1.16.4
Forge: 35.1.4

**Comment by alexnmt** [comment]
Mod Version 2.1.4-1.16.4

Forge 35.1.12

When you put the beastiary with 3 manuscripts in the lectern, you can learn a topic. When you exit the lectern, the manuscripts re-appear and you can learn another topic. You can do this over and over again, meaning you can learn the whole beastiary with just 3 manuscripts once you have created the lectern and beastiary itself.

It happens when no other mod is installed (besides JEI, not tested without JEI)

**Comment by TheBv** [comment]
This happens because two instances of the ContainerLectern class get instantiated.
One from the IafContainerRegistry class and one from the TileEntityLectern class, the latter has the information we actually want.
When the user opens the lectern each time he "enchants" the book both instances try to add the entry to the book.
But the one instantiated from the IafContainerRegistry does so first. Therefor the inventory from the second instance doesn't get changed (since the book already has the entry added) and therefor the pages once the user takes them out get reset.

One really stupid (and probably not good) fix would be to not check for the variable didEnchant, when changing the amount of manuscript pages.

**Comment by Glemoyn** [comment]
I am still getting this bug in the 2.15-1.16.4. I mentioned this in issue  #3206, but found this thread after I commented and wanted to mention it here so they can be merged if need.
I am using Ice and fire 2.15-1.16.4 on a server (additional mods on server are Botania, Astral, Blood Magic, Create, Corail Tombstone, Biomes o Plenty, Waystones, Immersive Engineering, Jei and TheOneProbe, FTB Chunk, FTB Gui and all dependencies)

To recreate, place at least 3 manuscripts in Lectern with bestiary, click on research topic, exit lectern GUI and re-enter, the three manuscripts you used will be duplicated so you will have the same amount as before. If you use 3 manuscripts and remove any remainder from the lectern, when you leave and re-enter the GUI they will be duplicated in your inventory.
