### ISSUE TITLE
Tombstone mod

### ISSUE THREAD

**Issue by TheJulen1999** [Alex-the-666/Ice_and_Fire#3373]
When an Ice Dragon or Fire Dragon throw a fireball/ice ability it brokes the player tombstone.

**Comment by Corail31** [comment]
I think this mod prefers to use its own way to handle indestructible blocks than relying on what is set in vanilla ;)
https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/entity/IafDragonDestructionManager.java#L43
https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/entity/util/DragonUtils.java#L308
Instead, they use a hardcoded list of blocks and a config option to set the blacklisted blocks.
NB : in vanilla, a block is indestructible if the hardness is set to -1 and there's also a method :
```java
    public boolean canEntityDestroy(BlockState state, IBlockReader world, BlockPos pos, Entity entity) {
        return false;
    }
```
Alternatively, there's also the possibility to use tag allowing modders to add their blocks easily instead of an interface asking for a hard dependency(IDragonProof).

**Comment by WeedTasteGood** [comment]
> I think this mod prefers to use its own way to handle indestructible blocks than relying on what is set in vanilla ;)
> https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/entity/IafDragonDestructionManager.java#L43
> https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/entity/util/DragonUtils.java#L308
> Instead, they use a hardcoded list of blocks and a config option to set the blacklisted blocks.
> NB : in vanilla, a block is indestructible if the hardness is set to -1 and there's also a method :
> 
> ```java
>     public boolean canEntityDestroy(BlockState state, IBlockReader world, BlockPos pos, Entity entity) {
>         return false;
>     }
> ```
> 
> Alternatively, there's also the possibility to use tag allowing modders to add their blocks easily instead of an interface asking for a hard dependency(IDragonProof).

May I ask whether there is any way to solve this problem temporarily before ice&fire creator made any decisions? (Except keepInventorytrue command) Thanks!
