### ISSUE TITLE
Сhunks stop loading

### ISSUE THREAD

**Issue by GnomTocha** [Alex-the-666/Ice_and_Fire#3375]
After long flights around the world, my chunks stop loading. Most often found in snow biomes. I'm not sure exactly what this mod caused, but after uninstalling it, I haven't encountered an issue yet.
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5760677/latest.log)
[debug.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5760678/debug.log)
![2021-01-02_18 26 04](https://user-images.githubusercontent.com/75666317/103463792-2e011280-4d40-11eb-9151-967d644e52dc.png)
![2021-01-02_20 03 30](https://user-images.githubusercontent.com/75666317/103463794-32c5c680-4d40-11eb-8073-273537e00e0f.png)

**Comment by drakray** [comment]
Hi there, I got this too, try setting "Generate Mausoleums" = false in your config/iceandfire-common.toml, I think it fixes this temporarily, as I found the chunk blocked when using WorldPregen always near one, found out with Minutor.
Since I disabled them, I have yet to experience this, for now at least.

**Comment by TheBv** [comment]
This will be fixed in the next release. #3359
