### ISSUE TITLE
Breeding issues, Stage 4/5 dragons spawn on surface, Safe Zone not working

### ISSUE THREAD

**Issue by WeedTasteGood** [Alex-the-666/Ice_and_Fire#3385]
Minecraft version: 1.16.4
Forge version: 35.1.28
Ice&Fire version: 2.1.4-1.16.4

1. Hippogryphs do not breed even they have breeding animation (get near each other)
2. Giving fire lily mixture to tamed dragons (Opposite gender, Same species, Stage 4/5, Both chained, Male wandering and Female sitting) will draw the male's aggro towards the female (Male hurting female). Breeding might be successful (An egg is layed) in this situation (which is strange)
3. Stage 4 and 5 dragons are able to spawn on the surface without any caves nearby 
4. Dragons, temples and other structures are able to spawn near spawn point (It might be caused by VillageSpawnPoint)

**Comment by TheBv** [comment]
Dragons not spawning near the spawn point only works around coordinates 0,0 .
I'm assuming since you're spawning near a village your coordinates aren't 0,0 so dragons can spawn there.

I can't seem to be able to recreate the third item on your list :| I did exactly the same you did and it didn't happen for me. I could only imagine that you might've accidentally hit one of the dragons. If you can recreate this yourself let me know exactly how and I'll get to it.

**Comment by WeedTasteGood** [comment]
> Dragons not spawning near the spawn point only works around coordinates 0,0 .
> I'm assuming since you're spawning near a village your coordinates aren't 0,0 so dragons can spawn there.
> 
> I can't seem to be able to recreate the third item on your list :| I did exactly the same you did and it didn't happen for me. I could only imagine that you might've accidentally hit one of the dragons. If you can recreate this yourself let me know exactly how and I'll get to it.


What I have done (as I recalled) is listed below:

1.Opened a new world. 
2.Using creative treats to tame two dragons ( If I remember correctly, the male one is red and the female one is black). 
3.Feed them both to tier 5 max size (125 days). 
4.Chain the male and set the female on sitting.
5.Then using fire lily mixture on both (male first).

Note that not every time this problem emerges.

On top of that, I think it is also quite weird if tamed dragons will attack each other if the owner hits it (Based on what you said). Shouldn't it like vanillia animals just stay idle?

**Comment by TheBv** [comment]
Honestly I agree with you that tamed enemies that have the same owner shouldn't attack eachother.
But I can also see why you'd want them to be able to (e.g dragon fights or something). Since I don't know what Alex wants I might, if I have the time, create a pull request that would add an option for if you want your tamed dragons to attack other tamed creatures. Something like "Dragons can attack tamed animals" and "Dragons can attack tamed animals with the same owner".
Alex then can decide if he wants it or not. 

Oh issue 1 should be fixed in the next release.
I couldn't see how stage 4/5 dragons could spawn without caves unless the cave gen messed up, or the dragon got teleported to the surface.
But there was an issue where a dragon with an age of 73 days could spawn in a roost, which I fixed in my draft, so hopefully that solves the issue partially.

**Comment by WeedTasteGood** [comment]
> Honestly I agree with you that tamed enemies that have the same owner shouldn't attack eachother.
> But I can also see why you'd want them to be able to (e.g dragon fights or something). Since I don't know what Alex wants I might, if I have the time, create a pull request that would add an option for if you want your tamed dragons to attack other tamed creatures. Something like "Dragons can attack tamed animals" and "Dragons can attack tamed animals with the same owner".
> Alex then can decide if he wants it or not.
> 
> Oh issue 1 should be fixed in the next release.
> I couldn't see how stage 4/5 dragons could spawn without caves unless the cave gen messed up, or the dragon got teleported to the surface.
> But there was an issue where a dragon with an age of 73 days could spawn in a roost, which I fixed in my draft, so hopefully that solves the issue partially.

Nah I don't really want them to fight each other. After all, stage 5 dragons are disasters XDDD. Did I need to show my modlist for you to see any of them causing the problem?
