### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kowantify** [Alex-the-666/Ice_and_Fire#3390]
https://pastebin.pl/view/65a5f014

This crash occurs when im loading chunks whilst flying/walking and it only crashes when that one big structure is made, the black one. I can't remember the specific name but everytime it tries to generate one the game will crash, every single time

**Comment by Won-Ton** [comment]
Hi. Quick pointer for the dev(s):
https://github.com/Alex-the-666/Ice_and_Fire/blob/7474393d44a5c0db9afed4d517810182e58aa4ab/src/main/java/com/github/alexthe666/iceandfire/world/structure/MausoleumPiece.java#L49

`MutableBoundingBox  p_230383_5_` is the bounding box of the chunk you're supposed to be restricting your structure piece to.

By expanding it you're opening up the possibility for Entities and (in this case) TileEntities that place outside of the Chunk to request new chunks from the ServerWorld >> ChunkProvider which it can't handle because it's busy trying to generate _this_ chunk. This agnostic of ChunkGenerator type.

**Comment by mossthey** [comment]
Just made my account to say I am also having this issue.

**Comment by AlessandroPozzi96** [comment]
Same issue over here, when my dragon turn around my house the game crash after 30sec...
