### ISSUE TITLE
1.16.4 Server compatibility issues

### ISSUE THREAD

**Issue by Shimakaze-poi** [Alex-the-666/Ice_and_Fire#3392]
The same problem occurs on both the Mohist and Forge server sides:

① The following error occurred when loading the module
"[modloading-worker-2/ERROR] [minecraft/Util]: No data fixer registered for ………………"
"[main/WARN] [minecraft/EntityDataManager]: defineId called for: class com.github.alexthe666.iceandfire.entity.EntityHippogryph from class com.github.alexthe666.iceandfire.entity.EntityPixie"
"[main/WARN] [minecraft/EntityDataManager]: defineId called for: class com.github.alexthe666.iceandfire.entity.EntityDreadThrall from class com.github.alexthe666.iceandfire.entity.EntityDreadKnight"

② Mods disappear and cannot be summoned by Spawn Eggs (single player does not have this problem)

**Comment by TheBv** [comment]
The things you posted shouldn't cause the issues you mentioned.
The "[modloading-worker-2/ERROR] [minecraft/Util]: No data fixer registered for ………………" errors aren't of any concern since data fixers are only being used for converting an entity from a really old version of minecraft into a newer one.
The other things are warnings and also shouldn't cause the problem you've mentioned...

If there's any other parts of the logfile that throws an error please post it. Or just post the whole logfile and I'll take a look at it.

**Comment by L00T3RK1NG** [comment]
I do have the same problem. I downloaded the error file
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/5862738/latest.log)
