### ISSUE TITLE
Server Config

### ISSUE THREAD

**Issue by villarjr** [Alex-the-666/Ice_and_Fire#3408]
We wanted to nerf rates, and health points from certain mobs in the server, I lowered it in config but it wasn't successful as it was only the common file, is there a server config anywhere within the mod? How do we go about changing the mods config within a server?

**Comment by TheBv** [comment]
Are you certain that the common doesn't change anything?
It should apply to the server but just keep in mind that currently you can't change any values for items. 
It's a forge limitation since the items get registered before the config file gets loaded.
I'm looking into some ways to get around that but with no success so far.

**Comment by FurryApocalypse** [comment]
I for example can't change the armor and sword damage in common (latest update singleplayer). Checked several times. Items value stays the same.

**Comment by Crazydude323** [comment]
Can confirm, changing dragonsteel sword and armor damage/armor values in the config doesn't actually change the values in-game.

**Comment by HendersonT** [comment]
I'm having the same issue, and there isn't any Ice and Fire Config in the World server files that I can find. Anyone know how to implement config changes to a server with this iteration?

 I am trying to turn on the fix for the "vehicle moved strangely" bug and it doesn't seem to be being implemented on the server when I change the common config file, unless I am misunderstanding how that option works? I haven't tested it out while riding dragons yet haha, just horses and the rubber banding is pretty bad despite a low mean tick time on the server.
