### ISSUE TITLE
dragon teleport crystal problem

### ISSUE THREAD

**Issue by ufeibfwebjgkgjs** [Alex-the-666/Ice_and_Fire#3428]
So when i use the crystal on a dragon and then use it again to recharge it  and when i put my dragon in a dragon horn and then out of the horn if i use the crystal it no longer teleports it

**Comment by TheBv** [comment]
I don't think there's a way around this, since the horn literally removes the entity from the world and then if you use it again it places a new entity with the same data into the world. The issue with that is that the id gets changed when doing that so the entity maybe has the id "4" before but after that has the id "7". 
And the crystal basically saves the id of the entity you've selected so it's trying to teleport the entity with id "4" to you but there isn't one anymore. 
The only way it would be fixable (without way too much effort like creating a new dimension where the entity you've selected with the horn gets stored) is if the crystal would basically do the same as the horn but that's kinda dumb. 
So yeah there's no way around this sadly sorry :|

**Comment by tweakbsd** [comment]
I'm working on a fix for this but it's not ready for public yet. Next week it should be done. I'm basically saving all dragonhorn interactions in world data to keep track which entity ID it was before and after use. then when summoning a dragon fails I go look at the world data if I find a dragon that had the appropriate ID before it was put into a horn. But as @TheBv said it's a lot of effort to get this to work. And do right of course.

**Comment by tweakbsd** [comment]
@TheBV I have found an elegant and easy solution for this Issue, I need to create a PR stil but here's the commit if you're interested in:

https://github.com/tweakbsd/Ice_and_Fire/commit/079870afc0eb690708c5a38bf7d6dd8fac8b1c0a

I forgot the idea of storing all UUID changes in world data and simply restore dragons from horn using their previous UUID which leaves all summoning crystals intact. :-) my testing so far went well.
