### ISSUE TITLE
Pathfinding Crash?

### ISSUE THREAD

**Issue by Yourname942** [Alex-the-666/Ice_and_Fire#3437]
Minecraft 1.16.4
Forge 35.1.29
Ice and Fire 2.1.5-1.16.4

"A player saw a dragon, and it disappeared and teleported" and then the server crashed. I'm not sure what I can do about this. Thank you.

This is what he was seeing when it happened: (dragon at 0:17 seemingly teleports at 0:20) https://clips.twitch.tv/AmazonianModernChoughSoonerLater

crash log: https://gist.github.com/Yourname942/a7eea5798ffd50406ae78cd5c8d6936c
latest log: https://gist.github.com/Yourname942/21ed7c88f360e7cdc0494c7e821e8dbc

**Comment by TheBv** [comment]
I know this is a bit of a stupid idea but can you try redownloading the mod? The error you're getting is basically saying that it can't find a file. So I'm hoping it's because of a corrupt download. 
I sadly have no other idea as to how to fix it.
Edit: apparently you're not the only one with the issue I'll implement the fix from the rats mod mentioned by the user here #3449
