### ISSUE TITLE
Ice and Fire configs are ignored when using "terraforged" level type

### ISSUE THREAD

**Issue by Tombstone101** [Alex-the-666/Ice_and_Fire#3468]
Prior to changing the level type of my server all configs behaved. After using the mod TerraForged and the "terraforged" world type ice and fire's config is ignored. Examples being cockatrices running rampant when config has spawning set to false, dragon nests right at spawn when config has distance set at 1500 from spawn, and etc. I have submitted an issue to TerraForged issue tracker and they tell me it's nothing on its end, and suggests it's an ice and fire issue. So here we are.

**Comment by Neko2n** [comment]
Not having this issue and I have the two mods paired. Cockatrices are set to only spawn in savannas with a low spawn rate, and I rarely see them ONLY in savannas. Dragon skeletons are disabled, I have never seen one. I set Gorgon Temples to spawn in forest biomes instead of beaches to prevent the water glitch, they're all over the place in forests.

Whatever this issue is, it's most likely a problem with your configs or your mod version (or it's a problem with another mod that isn't mentioned in your logs; do you have any other entity spawning or world generation changing mods?), as I have 205 mods along with Ice and Fire and Terraforged and both of them are working perfectly fine with each other.

**Comment by Tombstone101** [comment]
Im glad to hear these 2 can play nice together. I love terraforged and my kids wont play without ice and fire. I play with 140ish mods. Many of which add mobs and world gen structures. And like i said all worked as configured unless using terraforged as level type. Ill try removing mods adding worldgen 1 by 1 to see if I can narrow it down to any other mod particularly. At work now, will post any progress i find. Thanks

**Comment by Tombstone101** [comment]
After removing every mod adding world gen there was no change in unwanted mob spawning and world gen configs. However deleting my entire config folder and starting over seems to have "remedied" my problems and worldgen now respects config changes. I do not know which mod config or specific config option caused this or fixed this but I have resolved this issue.
