### ISSUE TITLE
Spawn ice and fire mobs close to spawn 

### ISSUE THREAD

**Issue by Th3lonehunter** [Alex-the-666/Ice_and_Fire#3518]
Hi was not able to see this anywhere but i wanted to know if it is possible to set the "safe zone" to be smaller so the mobs spawn closer to the world spawn point. i ask as on our server we have our main settlement set up by this spawn point.

**Comment by Syrikal** [comment]
Yes. In the config, change this value:
![image](https://user-images.githubusercontent.com/76715986/106999393-b746a300-674b-11eb-8e51-40ab46219fa3.png)
Do note however that because these dangerous structures are generated with the world, this will have no effect on already-generated chunks, so if you've already made the world and explored near spawn then there's nothing you can do.
