### ISSUE TITLE
Dead dragons corpse still getting targetted

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#3600]
Even afteryl you loot the corpse and it disappear, the enemies still try to attack it

**Comment by TheBv** [comment]
With "enemies" do you mean that every entity attacks the dragon corpse or only other dragons?

**Comment by kihgy** [comment]
The mobs that was attacking the live dragon will continue to attack the dead one, while dragons enemies such as the dread wont if they are spawned after the dragon is dead.

**Comment by Chumbanotz** [comment]
The reason for this seems to be because of this line, which considers the dragon to be alive when its model is dead. Mobs usually check the `isAlive` method to start and stop attacking
https://github.com/Alex-the-666/Ice_and_Fire/blob/6648393a3bc243888ac2509c3cd1c36924489407/src/main/java/com/github/alexthe666/iceandfire/entity/EntityDragonBase.java#L1041
I'm not sure why it was implemented this way, but I know [this ](https://github.com/Alex-the-666/Ice_and_Fire/blob/6648393a3bc243888ac2509c3cd1c36924489407/src/main/java/com/github/alexthe666/iceandfire/entity/EntityDragonBase.java#L1048)method prevents dead mobs from being interactable since [MC-76416](https://bugs.mojang.com/browse/MC-76416) was fixed. I recommend removing the `isModelDead` check in the `isAlive` method, and then move [this ](https://github.com/Alex-the-666/Ice_and_Fire/blob/6648393a3bc243888ac2509c3cd1c36924489407/src/main/java/com/github/alexthe666/iceandfire/entity/EntityDragonBase.java#L1055)code to the method`applyPlayerInteraction` which will allow a player to interact (right-click) a dead mob.

As an example, I use this method [here](https://github.com/Chumbanotz/MutantBeasts/blob/2fc4a87636e1d3b078f239fa9e0c2ab409360b45/src/main/java/chumbanotz/mutantbeasts/entity/mutant/MutantZombieEntity.java#L206) to allow a player to interact with the mob when it's dead.

**Comment by TheBv** [comment]
Yeah the reason why the isModelDead is there is because otherwise you wouldn't be able to interact with the entity after it's dead. This is probably still some code from a couple of minecraft versions ago. 
I'll give your suggestion a shot and implement it in my PR thanks for the info!
