### ISSUE TITLE
Too many Cyclops [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Ice_and_Fire#3619]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
With the rate of 1 out of 100, there are just too many wandering Cyclops

**To Reproduce**
1. Go to a plains biome with the default rate

**Expected behavior**
Wandering Cyclops should be rare than Gorgon temple

**Screenshots**
![2021-02-27_06 47 15](https://user-images.githubusercontent.com/54225061/109367996-3b62f500-78ca-11eb-969d-07851d7c6028.png)

**Additional context**

**Comment by Neko2n** [comment]
I'm assuming you have your biome configs set to the default values (unchanged), so I'm assuming Wandering Cyclopses are supposed to spawn in plains while gorgon temples are supposed to spawn on beaches.

Gorgon temples have a 1/75 chance to generate. This should make them spawn _more_ commonly than wandering cyclops, but they only generate on beaches like Cyclops Caves; this means they spawn far less than you'd think due to the limited space they have to generate (beach biomes are often very short and thin).

Wandering Cyclops can generate on any terrain. Their only requirement is that the biome they spawn in is a Plains biome. Plains biomes are very large (MUCH larger than beach biomes) and have lots of flat, open space to generate Wandering Cyclopses. Therefore, instead of being rarer than gorgon temples, they actually spawn far more because they have more _opportunities_ to spawn more.

Weight/chance isn't usually the only factor in deciding if a mob or structure can spawn. Spawn location and terrain also matter for many mobs and structures.

This isn't really an issue from what I can assume, and I have wandering cyclops set to spawn in forest and plains biomes and I'm having no issues. I simply set the spawn rate to 1/300 instead of 1/100, and they're spawning somewhat normally. Try setting weight higher in your config; if you no longer have a problem, this issue should probably be closed.

**Comment by kihgy** [comment]
Okay that much more sense I will close this issue for now, never know about this
