### ISSUE TITLE
Ice and Fire 2.1.6 Hippogryph control

### ISSUE THREAD

**Issue by dwiantlake** [Alex-the-666/Ice_and_Fire#3635]
The gryphon control kinda messed up after the update
now it always go slow first before doing something either dive front/ dive to bottom/ etc. 
It's good for a long flight but if I just want to check around its kinda annoying.

**Comment by Cisceaugh** [comment]
---
name: Bug/Issue
about: Report bug or issue with ice and fire. NO SUGGESTIONS HERE!
title: Issue desc [ICE AND FIRE VERSION]
labels: ''
assignees: ''

---

**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Hippogryph controls become unresponsive upon stopping momentum midair. 

**To Reproduce**
Steps to reproduce the behavior:
1. Mount a tamed hippogrpyh
2. Hold space and "W" to ascend and fly forward
3. Cease all momentum and hover in place
4. Attempt to fly in any of the cardinal directions and/or ascend or descend
5. The hippogryph will not respond to player controls
6. Dismounting will cause the hippogryph to hover in place midair
7. Upon relogging the hippogryph will be on the ground

**Expected behavior**
The hippogryph movement controls should remain response whether or not the player chooses to hover midair.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
