### ISSUE TITLE
Fire Dragons Spawing in Snowy Mountains [2.1.6]

### ISSUE THREAD

**Issue by duke-scott** [Alex-the-666/Ice_and_Fire#3645]
**Describe the bug**
Fire Dragons are spawing in Snowy Mountain biomes.  I have found 3 examples of this.

**To Reproduce**
Find dragon roosts in snowy mountain biomes.

**Expected behavior**
Ice dragons should spawn in snowy mountains.

**Screenshots**
![2021-03-01_15 21 13](https://user-images.githubusercontent.com/79550623/109730271-dd126c80-7b7e-11eb-8026-594f3872bf92.png)
![2021-02-28_17 14 29](https://user-images.githubusercontent.com/79550623/109730278-df74c680-7b7e-11eb-88a0-490ad32c97ca.png)

**Additional context**
Server:
Minecraft 1.16.5
Forge 36.0.42
Citadel-1.6.1
iceandfire-2.1.6-1.16.4

Client:
Minecraft 1.16.5
Forge 36.0.43
Citadel-1.6.1
iceandfire-2.1.6-1.16.4
OptiFine_1.16.5_HD_U_G6

**Comment by TheBv** [comment]
For someone reason biomes that are snowy and mountainous were allowing fire dragons to spawn there.
If you want you can go into your config folder /iceandfire/fire_dragon_biomes and remove the snowy tag/the last overworld/mountain/snowy entry. That should fix the issue for you in the meantime.
Oh also make sure you update to Citadel 1.6.2! Otherwise jungle myrmex and fire dragon skeletons won't generate!

**Comment by duke-scott** [comment]
Thanks.
