### ISSUE TITLE
Hippogryphs are extremly buggy (flying bug)

### ISSUE THREAD

**Issue by IamBreadstick** [Alex-the-666/Ice_and_Fire#3677]
**Describe the bug**
In version 2.1.6-1.16.4, Hippogryphs are completly broken:
-Wild hippogryphs never land
-Some variants never naturally spawn ( gray, white, creamy)
-Baby hippogryphs are untamed when hatched
-When tamed they glitch out curing their front and back feet into themselves, after doing that if you saddle them and try to ride them they dont move, and they ocationally are able to fly directly up but when that happens they keep flying up even when unmounted after that they proceed to fly up  

**To Reproduce**
Tame a spawned or naturally spawned hippogryph (if it somehow lands), throw it some rabbits feet and saddle it.
after you mount it, it is uncontrolable and wont move with w,a,s,d. Space bar sometimes works but glitches them out further.
If you dismount mid air the hippogryph stays stationary and flies up (it doesent always fly up sometimes it stays stationary at the location you dismounted it). The only way that the hippogryph drops back to the ground is if you hit it with a frost dragonbone sword

**Expected behavior**
After taming it should sit down and wait, then you should saddle it and mount it after whitch you should be able to fly it and control it.

**Screenshots**
This hippogryph was hatched. It stays in that position until hit with a forst dragonbone sword. Wild hippogryph behave the same. (this is on a singleplayer world, i opened the world to lan to get into creative mode to take the screenshot.)
![Untitled](https://user-images.githubusercontent.com/80411217/110658626-1facf800-81c2-11eb-9681-c770e8d6790d.png)

**Comment by kihgy** [comment]
On the side note, amphithere suffer the same flying issue where they will never land, but not as broken.

**Comment by IamBreadstick** [comment]
so im guessing that the devs have so many reports about hippogryphs they dont bother with most reports?

**Comment by PGal404** [comment]
I have the same problem. The hippogriff is extremely bugged. Wild hippogriffs will never land (I followed one for more than 4 hours, it was very stressful) ... Once tamed the hippogriff has enough trouble "sitting as it should be". However, this does not affect anything, it just looks weird. What really affects is that the hippogriff does not respond well to being handled, as long as you do not stop flying, everything is fine, but if you stay still, you will have to spam the button to descend until the hippogriff descends. And only when it is on the ground can you move it again, when it stands still it is impossible to move it again in the air. And also, the worst bug. If you dismount from the hippogriff while it is in flight, it will begin to rise to infinity. This is something that always happens, if you disassemble it the flight will always continue to rise. I even had to go rescue my hippogriff from Y = 1600. I just hope they fix this soon, because while dragons are great, I really love hippogriffs for how cute, small, practical and easy to carry they were.
