### ISSUE TITLE
Gorgon Temples flooded with water

### ISSUE THREAD

**Issue by hassan94935** [Alex-the-666/Ice_and_Fire#3678]
Every Gorgon Temple that spawns is flooded with water even though there’s no breach on the walls.

![486125F7-A517-4CD7-A6F1-AB04E02F3A9C](https://user-images.githubusercontent.com/80424869/110691864-71ef1880-81c4-11eb-8b7c-0fa3e0f4ad02.jpeg)
![B12DB7FF-AA11-42F0-922F-A9FC681A9E30](https://user-images.githubusercontent.com/80424869/110691870-73b8dc00-81c4-11eb-9ab0-55123bb27c0c.jpeg)

**Comment by TheBv** [comment]
This is a bug with minecraft that will be fixed in the next version. I can't find the issue anymore but basically whenever you place structures based on nbt-data into the world the waterlogged status gets overwritten if there's water where the block should be placed at.

**Comment by TelepathicGrunt** [comment]
The issue seems to be compounded by using the land terraforming list for non-jigsaw structures as it will attempt to level the land and open up the space for every piece itself. When below sealevel, the open space the terraforming does will place water when then triggers that minecraft bug. I can convert your structure to jigsaw and make a PR. The jigsaw structure will make the terraforming only happen on the top piece and prevent 99% of the flooding
