### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION] Gorgon head used against a player with a totem of undying crashes the world

### ISSUE THREAD

**Issue by Zombierunner09** [Alex-the-666/Ice_and_Fire#3679]
**Describe the bug**
When a gorgon head was used against another player on a server, the stone statue produced was very buggy. It would cause the game to crash repeatedly. Additionally If a gorgon head kills a player with a totem of undying, then the game will crash.

**To Reproduce**
1. On a server a player should hold a totem of undying.
2. Then another player should use a gorgon head targeting the player.

**Comment by TheBv** [comment]
Could you send the crash-report/ debug.log? 
I wasn't able to recreate this yet :|

**Comment by Zombierunner09** [comment]
Thank you for getting back to me so swiftly! Unfortunately I didn't collect
any of that the first time that it happened. I attempted to recreate it
again multiple times with multiple different situations and I was unable to
cause any issues. I think it must have been something unrelated, I'm so
sorry to have wasted your time on that. Thank you for looking into it, and
I do think that you are doing a fantastic job with this mod! Keep up the
good work!

**Comment by TheBv** [comment]
@Zombierunner09 
Minecraft collects them automatically and stores them "forever" unless you've deleted them manually they should still be there.
If the crash happened on the 5th of March the log file would be called: 2021-03-05-X.log.gz (where X is a number) in the /logs folder. It's best to just look at the modified date since that also includes the time they were created. 
If you don't have them anymore don't worry! But it might be worth to take a look.
Thanks for the PR and the response! :)
