### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Paique** [Alex-the-666/Ice_and_Fire#3693]
Hi, so a Gorgon is causing people to disconnect from the server.

Whenever someone gets close to the chunk he is in, he gets disconnected with the error on the printout, so I need to teleport the person to a distant location as soon as he connects, otherwise he can't play.

Here is the error: 
![image](https://user-images.githubusercontent.com/57367252/111043500-af041680-8421-11eb-8ae1-13517fd9875e.png)

This all happened right after he killed me, since then the chunk is inaccessible.
The server console does not show any errors, only that the person has been disconnected.

**Comment by TheBv** [comment]
Would it be possible for you to post the server debug log as well as your log file when the crash happened? Would be very much appreciated!

**Comment by Natybo** [comment]
I'm also experiencing this error on my server. I have to delete their player data to get them back into the game, or TP them the moment they log in.

**Comment by TheBv** [comment]
> 
> 
> I'm also experiencing this error on my server. I have to delete their player data to get them back into the game, or TP them the moment they log in.

Could you possibly provide logs? Without them it's really difficult to judge what's happening.

**Comment by Paique** [comment]
I can't, because I had to format my computer where I run the game and the server: /

**Comment by Paique** [comment]
I was able to recover some files from the old hard drive that crashed, by the way, the " [13Mar2021 16:49:44.936] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: No entity was found" was me spamming the console to get out of the chunk.
[2021-03-13-2.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6176581/2021-03-13-2.log)

**Comment by TheBv** [comment]
There's sadly nothing being logged that would tell me what's happening. I have looked at similar error messages and I don't think that they would actually be useful sadly. From what I gathered these crashes usually occur if an entity's nbt data is too large. So that'd either be an item or a mob or technically some blocks with inventories (gravestones, chests etc.).
If we look at what @Natybo says it looks like in his case it was an item since by deleting their inventory that seems to have fixed it. In your case it could also be an item just maybe laying on the ground instead of being in your inventory.
Do you remember if you had any item in your inventory that had nbt data attached to it?
The other possible thing to look into would be the stone statues the gorgon creates. I'll have a look at those and try some things out to see if I can recreate this issue.
So question now is which item is causing the issue.

**Comment by Natybo** [comment]
I dont think its just one item. As its happened to multiple players on my server, at multiple temples.
I'm trying to recover logs and look into it.

**Comment by TheBv** [comment]
If you could post a list of mods that'd be cool as well. Maybe it's a compatibility issue.

**Comment by VampireTechnologyLord** [comment]
`Payload cannot be larger then [bytes]` always means that something is exceeding the memory limit. This is usually either because of extremely much data in a player inventory (due to backpacks or other things that need large amounts of data to be stored) which will result in the player being unable to join. That player will then get a similar message. I think in you're case it's that the gorgon has made a large amount of statues in this one chunk (which will all have stored data(health, attributes, when they got transformed...) that the chunk is exceeding the limit of data a chunk is allowed to have. That way, when ever a player enters the chunk, minecraft tries to load the data but fails because of this large amount of data and the player get's disconnected.

Possible solutions:
1. load an older backup of that chunk, where there isn't thet much data stored in it
2. prevent players from joining the chunk

I hope that was helpful ;)
