### ISSUE TITLE
Config not working as intended or maybe at all [iceandfire-2.1.6-1.16.4]

### ISSUE THREAD

**Issue by ShootToKillSTK** [Alex-the-666/Ice_and_Fire#3694]
**Describe the bug**
Config for blacklist/whitelisting structure and mob spawning doesn't work seemingly

**To Reproduce**
See image attached, accidentally asked on discord so screenshot that and posting here, should show everything needed

**Additional context**
Was pretty unmodded, barely any other mods used, biggest was repurposed structures, no other biome mods for my testing, optifine, neat and spawnbalanceutility was all that was used, only ice and fire was edited

![image](https://user-images.githubusercontent.com/78947563/111085163-63aa4080-84d3-11eb-9c6d-a01e0d24e4c4.png)

**Comment by TheBv** [comment]
The way you configure the biomes has been changed in version 2.1.6 there's a sub folder now called iceandfire with .json files in which you can configure things.
The stuff with the blacklist whitelist probably doesn't work anymore (in the common file). I'll have to take a look at that it might need updating.
Edit: They should still work but they are a bit confusing to work with. By setting use dimension blacklist to true and setting the blacklistDimensions to [""] you basically say that nothing should be blacklisted. More importantly the whitelist right now is the same as the blacklist... So you're definitely correct when saying that things don't work properly. This probably explains all the other issues of mobs not spawning...

I think there should actually be separate whitelists and blacklists for each "mob" so one for dragons one for cyclops/hydras and one for other mobs like Trolls. I'll create a PR soon in which I either enable them again or remove them completely... but until then I'd recommend editing the .json files they should work 100% of the time. Just keep in mind that in order for them to work it's best if you use the current config settings you have posted above. Otherwise they might overwrite things.

**Comment by TigersFangs** [comment]
I have a similar issue, but with the block blacklist rather than the biome list. I thought that I would bring it up here as opposed to starting a new issue. If that is needed I would be happy to do so.

I am currently building a very small fantasy steampunk mod pack with things like Create, Minecolonies, and Mana And Artifice. I would like to build a custom list of blocks that they can/cannot break. Honestly a whitelist would be easier, but I can work with it. 

The issue that I’m having is that no matter what I do, it doesn’t seem to take effect. I have tried as directed in the config. I’ve tried with and without quotes. I’ve tried both vanilla and forge references. Nothing seems to work. The only thing that makes a difference is the basic setting of Default, Weak, or None.

Current build is using:

Minecraft: 1.16.5
Forge: 36.0.45
Ice And Fire: 2.1.6-1.16.4

I’ve been meaning to update Forge to do more testing, but haven’t had the time.
