### ISSUE TITLE
dragons not rendering properly [ICE AND FIRE VERSION 2.1.6]

### ISSUE THREAD

**Issue by exploder94** [Alex-the-666/Ice_and_Fire#3696]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
The dragon appears as a blank white model with no details.  It appears to have pink rendering errors too where parts of the model will flicker pink.  

**To Reproduce**
This only happened with one dragon in the world and it was fine the first time I saw it.  The second time when I went back to fight it, it was buggy.  

**Expected behavior**

**Screenshots**
![2021-03-12_14 16 23](https://user-images.githubusercontent.com/80724390/111233357-151ba580-85aa-11eb-9cea-d6d59b46aad6.png)
![2021-03-12_14 16 29](https://user-images.githubusercontent.com/80724390/111233362-18169600-85aa-11eb-99d1-5f9e8876acab.png)

**Additional context**

**Comment by TheBv** [comment]
Could you possibly provide the debug.log file? I'm not sure if the thing you mentioned will be logged or not but it would be worth a shot.
This might be more related to citadel though than ice and fire hard to say. Reason I mention that is because when I messed around with how citadel renders things I've managed to get exactly the same thing happen except for the purple flickering. (I think it had something to do with the bytebuffer and the uv indexing)
If you relog/restart minecraft this should fix itself though right?

**Comment by exploder94** [comment]
I honestly am not sure what a .log file is.  Where would I find it?  A
directory is fine I know how to find those.

**Comment by TheBv** [comment]
Depends on where you've got minecraft installed. But in the minecraft install directory there's a "logs" folder and in that are all the log files. If they are older they will have a .log.gz file ending. Just select the one that has the date/time on it from when this happened. If you sort by date modified that would probably be the easiest way to find the right one.
If you don't know where your minecraft install is you can for instance take a screenshot and click on the text that pops up in the chat that's probably the easiest way to find it since there's so many different ways to install mods/a modpack.
