### ISSUE TITLE
language wont change

### ISSUE THREAD

**Issue by Mototsu666** [Alex-the-666/Ice_and_Fire#3719]
the language wont change ingame, even i spotted all the language files.
How to change the language?
is it a bug. i play on version 1.16.4
thx

**Comment by TheBv** [comment]
Ice and Fire currently only supports a handful of languages(german, spanish, russian, japanese, korean). Also it the current release the korean language is broken which will be fixed in the next version. The other languages should work just fine e.g german. If not let me know!

**Comment by Mototsu666** [comment]
it wont change to the german one :/ i dont know what to do

**Comment by SinobinU** [comment]
German don't work. 
Changelog: added german translation IS english!

**Comment by TheBv** [comment]
Whoops I lied the german translation file was also broken which I've already fixed.
If you want to play with translations you can download the current language file [here](https://github.com/Alex-the-666/Ice_and_Fire/blob/da802ec910cd8026009e938a08a421ea9b29e11e/src/main/resources/assets/iceandfire/lang/de_de.json) and open the current .jar file you've downloaded with 7Zip (or similar programs) and replace the \assets\iceandfire\lang\de_de.json file with the one you've downloaded. I'm technically not allowed to upload my own builds of the project since it doesn't contain a licensing file so that's all I can do about it :/

**Comment by Mototsu666** [comment]
thanks a lot, now it works <3

**Comment by SinobinU** [comment]
There are a few misspellings in the de_de file. Here are the corrected lines:

	"item.iceandfire.sapphire_gem": "Saphir",
	"iceandfire.sound.subtitle.naga_attack": "Naga greift an",
	"advancements.iceandfire.kill_sea_serpent.description": "Erledige eine Seeschlange.",
	"advancements.iceandfire.rotten_egg.description": "Erhalte ein verrottetes Ei",
	"advancements.iceandfire.kill_stymphalian_bird.description": "Töte einen stymphalischen Vogel"
