### ISSUE TITLE
Arrows Don't Work Correctly [1.7.1-1.12.2]

### ISSUE THREAD

**Issue by Drakaos** [Alex-the-666/Ice_and_Fire#3730]
Dragon Bone Arrows can't be fired and Tide Arrows cause blood splatters.

No matter what type of bow I use, the dragon bone arrows can't be fired. They also can't be put into quivers, which is odd. It looks like the game doesn't consider them to be arrows at all.

The Tide arrows can be fired and put into quivers, but every time I do so, a blood splatter appears on my screen, which usually only happens when I take damage. However, I don't take any damage from actually using the arrows.

I am currently playing on RLCraft if that helps. It's where the quivers and the blood splatter are coming from.

**Comment by Mewkitty22** [comment]
Hey, dude!

Just so you know, the folks building the mod have asked us to keep bug reports to the most recent version -- that's 1.16.5.

The issue you're describing was a known bug in the 1.12 versions and got fixed in later builds. As of 1.16, dragon bone arrows work fine!

I reccomend you upgrade to a newer version, if you're able to.

**Comment by AlexModGuy** [comment]
1.12 no longer supported
