### ISSUE TITLE
Banner problems [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Adowg565** [Alex-the-666/Ice_and_Fire#3798]
All of the banner patters are not showing and just turns the banner black regardless of whatever dye I use. It is only with the patterns this mod adds the normal Minecraft patterns and another mod I use “Additional Banners” patters do not do this. And it is not an issue with refined storage because I don’t have that.

![B9B06A05-83B2-49F7-BC75-B9C8E0D4E1C9](https://user-images.githubusercontent.com/82189698/114910262-854c5f80-9dd2-11eb-9c87-a61b78c4eb91.png)

![6371CB93-5D11-40F5-BF9B-535170626537](https://user-images.githubusercontent.com/82189698/114910272-88dfe680-9dd2-11eb-9285-5a472b3467ad.png)

![35D4E476-296E-4408-A94F-2B278000C638](https://user-images.githubusercontent.com/82189698/114910286-8d0c0400-9dd2-11eb-851d-e0817e9d1af3.png)

**Comment by TheBv** [comment]
Are there any other mods you have installed besides IaF and additional banners?
When investigating that issue before (in combination with refined storage) I found the culprit to be that some mod was during item registration at the wrong [time](https://github.com/refinedmods/refinedstorage/issues/2766) (at least as far as I'm aware).
The reason additional banners wasn't affected was because of the mod loading order. (I think forge loads them alphabetically, I could be wrong though)
Maybe refined storage is not the only mod with that issue?

**Comment by Adowg565** [comment]
Yes I am do you want a copy of the my modded folder

**Comment by wilyank** [comment]
I discovered that, for me, this was caused by Mowzie's Mobs
