### ISSUE TITLE
Server crash with gold pile block and Whisperwoods [1.16.5]

### ISSUE THREAD

**Issue by BugmanBugman** [Alex-the-666/Ice_and_Fire#3881]
[crash-2021-05-17_11.30.01-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6495383/crash-2021-05-17_11.30.01-server.txt)

**Comment by Zulenka** [comment]
Also getting this error. 

`Server thread/FATAL [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 75be95cd-d358-4288-b6fa-bd03ef717300
01.06 20:23:02 [Server] Server thread/ERROR Encountered an unexpected exception
01.06 20:23:02 [Server] INFO net.minecraft.crash.ReportedException: Ticking entity
01.06 20:23:02 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 20:23:02 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
01.06 20:23:02 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 20:23:02 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 20:23:02 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 20:23:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}
01.06 20:23:02 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/block/BlockGoldPile$1
01.06 20:23:02 [Server] INFO at com.github.alexthe666.iceandfire.block.BlockGoldPile.func_196266_a(BlockGoldPile.java:51) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196957_g(AbstractBlock.java:661) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:forgeendertech:randomTickBlock,pl:mixin:APP:passablefoliage.mixins.json:MixinBlockState,pl:mixin:APP:valhelsia_structures.mixins.json:AbstractBlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.WalkNodeProcessor.func_237238_b_(WalkNodeProcessor.java:500) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:WalkNodeProcessorMixin,pl:mixin:A}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.FlyingNodeProcessor.func_186330_a(SourceFile:291) ~[?:?] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.WalkNodeProcessor.func_193577_a(WalkNodeProcessor.java:350) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:WalkNodeProcessorMixin,pl:mixin:A}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.FlyingNodeProcessor.func_186319_a(SourceFile:257) ~[?:?] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.FlyingNodeProcessor.func_192558_a(SourceFile:321) ~[?:?] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.FlyingNodeProcessor.func_176159_a(SourceFile:228) ~[?:?] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.FlyingNodeProcessor.func_222859_a(SourceFile:87) ~[?:?] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.PathFinder.func_227479_a_(SourceFile:97) ~[?:?] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.PathFinder.func_227478_a_(SourceFile:45) ~[?:?] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.PathNavigator.func_225464_a(PathNavigator.java:129) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.PathNavigator.func_179680_a(PathNavigator.java:105) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.PathNavigator.func_225466_a(PathNavigator.java:90) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
01.06 20:23:02 [Server] INFO at net.minecraft.pathfinding.PathNavigator.func_75492_a(PathNavigator.java:142) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
01.06 20:23:02 [Server] INFO at net.minecraft.entity.ai.goal.FleeSunGoal.func_75249_e(SourceFile:67) ~[?:?] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41) ~[?:?] {re:classloading,pl:accesstransformer:B}
01.06 20:23:02 [Server] INFO at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:358) ~[performant:1.16.2-5-3.56m] {re:classloading}
01.06 20:23:02 [Server] INFO at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 20:23:02 [Server] INFO at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:better_diving:WorldRenderer Transformer,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:bigbrain.mixins.json:LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:assets/offhandcombat/offhandcombat.mixins.json:SwingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 20:23:07 [Multicraft] Skipped 108 lines due to rate limit (30/s)
01.06 20:24:03 [Multicraft] Server shut down (running)
01.06 20:24:03 [Multicraft] Restarting crashed server in 300 seconds
01.06 20:24:03 [Multicraft] Server stopped`

**Comment by Zulenka** [comment]
Confirmed that ANY mob trying to path onto a gold block pile crashes the server. At least on our server.

**Comment by BugmanBugman** [comment]
Sadly it seems like the mod is unstable for servers for the time being

**Comment by AlexModGuy** [comment]
#3938
