### ISSUE TITLE
Dragon burrowing to surface

### ISSUE THREAD

**Issue by Domikulas** [Alex-the-666/Ice_and_Fire#3926]
I was started a new survival world after 1 hour a Stage 5 dragon came out of nowhere.
I switched to creative beacuse i knew that this isn't a feature, they must stay in the they're "cage", but they broke the crackled stone and the treasure inside they're "cage". I created a new creative world and found a dragon who's breaking out.

https://imgur.com/a/if9R0ci

**Comment by RolledOverTurtle** [comment]
Actually this is an intended feature. This prevents them from being trapped when you fight them and they are also often popping out of nowhere to attack you which adds some spice to the mix. This is no bug.

**Comment by Domikulas** [comment]
> Actually this is an intended feature. This prevents them from being trapped when you fight them and they are also often popping out of nowhere to attack you which adds some spice to the mix. This is no bug.

I can't disable it?

**Comment by Lashriel** [comment]
You can disable DragonGriefing in the config (set it to the value for "no griefing"). This prevents them from breaking blocks, though it doesn't prevent their breath from turning blocks into their Charred/Frozen/Crackled variants - thus, they won't be able to "break out" of their cave.

As an alternative, setting it to "weak blocks only" will prevent them from breaking any ores, which also prevents them from reaching the surface since their caves are layered with high-mining-level ores - but still allows them to break anything that doesn't require a stone-or-better pickaxe so surface dragons are as destructive as ever.

Note that this makes underground dragons act *weird*. They will still *try* to break out of their cave, but be unable to.

**Comment by RolledOverTurtle** [comment]
You can disable it - though I wouldn't advise it as it makes them extremely vulnerable and weak when fighting. they can get caught on things easily and won't be able to do anything when you fight a tier 4-5 which makes them rather disappointing.

**Comment by ghost** [comment]
You should probably close this @Domikulas
