### ISSUE TITLE
Incompatiblity with Tantrum and The Abyss 2 [Latest Version 1.16.5] + fix

### ISSUE THREAD

**Issue by Y3Z0N** [Alex-the-666/Ice_and_Fire#3934]
theres a issue where dragons can have infinity levels when using the dragon horn.
minecraft detects the dragon in a entity join event.

Tantrum and TA2 can add levels to Entity Animals and Monsters when they spawn into the world (if in config enabled) 

A Solution:
we can fix this on both sides but i need your help for that..
i would be cool from your side when you can add a entity tag to your dragons as example "iceandfire:dragons"
so i can work on tantrum and ta2 to be compatible with ice and fire :)

please let me know the tag if you add them so i can work on a fix on my side too!

**Comment by MarkValhezia** [comment]
y3 you don't have to do anything on your side.
Alex needs to store the UUID in the dragon horn. when u use the dragon horn it changes the UUID every time you use it for your entity. its a bug on Alex side he have to add a checker for the uuid to store and save it instead of creating a entity join event every time / adding a new UUID

**Comment by AlexModGuy** [comment]
should be fixed indev
