### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 48004800** [Alex-the-666/Ice_and_Fire#3963]
1     The initial health value of sea serpent is not full
And their health will increase after reloading the archive    {not maxhealth}

2       Cannot modify defense value of equipment    by config    
dragonsteel
3     The durability of equipment cannot be modified   by config  For example, change it to unlimited durability
dragonsteel
 4    Can't modify dragon's charge attack damage  This results in uncoordinated attack damage
ice charge    fire charge   lightning charge

**Comment by TheBv** [comment]
From looking at the code I feel like Sea serpents not spawning with max health is intentional since basically after spawning the sea serpent heals itself for 30* the amount of scales it drops which seems quite specific.
I think the fact that this piece of code gets called every time you reload the entity isn't intended though so I'll try fix that.

With number 3. I'm assuming you are referring to the armor not being affected by the durability changes? Tools do seem to work for me.

Anyway thanks for the input I'll have a PR up soon fixing the rest of the issues :)

**Comment by 48004800** [comment]
I mean, I can't change the durability of armor  { by config}
version : 2.1.7
