### ISSUE TITLE
Config Impermenance [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by WealthyNigerian** [Alex-the-666/Ice_and_Fire#3995]
Whenever me or my friend attempt to change any config options for the mod, both server-side and client-side, upon launching, the settings revert back

**To Reproduce**
1. Change Config file
2. Launch Minecraft with Ice and Fire
3. Config Undoes itself

I Expected for whenever I change a config setting and or option, it remains changed instead of reverting back.

**Comment by pm065** [comment]
This is a bug with Forge, but I think I remember hearing it needs to be fixed on the author's side. You'll need to change the config outside the game, unfortunately.

**Comment by TheBv** [comment]
Which ice and fire version are you referring too?
Also I don't think you can currently change the config ingame(I actually didn't know forge allowed for things like that I might work on implementing that) so the only way to change it is to edit the actual files.
If you could provide the latest log that would help since it tells you which specific value forge thinks is malformed or if it's the entire file.

**Comment by pm065** [comment]
> Which ice and fire version are you referring too?
> Also I don't think you can currently change the config ingame(I actually didn't know forge allowed for things like that I might work on implementing that) so the only way to change it is to edit the actual files.
> If you could provide the latest log that would help since it tells you which specific value forge thinks is malformed or if it's the entire file.

Oops, I misread the post. (There is actually a mod called Configured that allow you to do that, though.)
I thought they were talking about editing the file while the game is running.
