### ISSUE TITLE
Gorgon Turning to Stone Crashes Server [2.1.8]

### ISSUE THREAD

**Issue by WordStormRose** [Alex-the-666/Ice_and_Fire#4076]
**Describe the bug**
Anytime a Gorgon turns a player to stone on a server, either via head or the gorgon herself, the player is forcibly disconnected with the error message shown in the screenshot. Anytime another player attempts to get close they are kicked as well.
We are using the modpack Lennbain, version 2.1.0. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54124339/126025931-76921567-658a-4847-8fab-e13f74f0d971.png)

**Comment by FlameyFaucet** [comment]
It looks like the statue possessed too much data for the game to handle, effectively turning the chunk it's in into a chunk-ban. Your best bet is somehow getting rid of the statue entirely from that area using...something.

If unable to, welp, your world is screwed. Better have some recent backups ready!

A fix would be to remove ice and fire, reload the server's stuff, and then try to join. Removing the mod should remove the statue as well, but this can cause unprecedented chaos. Try at your own risk.

**Comment by WordStormRose** [comment]
I'm currently deleting chunks serverside, which is what worked last time. However, not everyone would know how to do that so I am hoping a fix can be found.

**Comment by Disturbeddragon1** [comment]
Similar happens with the tombstone mod installed. All the same error except it doesn't say the NBT tag was too big but the Payload was too big where max allowed was 2097152. So if you can get a world edit program and reset the area it should be fine again and just make sure either you or the server admin moves you away from the mausoleum before re-logging in to the world. We are running the 2.1.8-1.16.5 version of Ice and Fire, the 1.16-6.4.7 version of Corail Tombstones, and Forge version 1.16.5-36.1.0 if that helps get the issue figured out. Really love the mod so would hate to get rid of it because of this.

It would seem though that if you have any tombstone mod installed and this happens, you loose all your stuff unless you have backup player inventory enabled in the tombstone mod. At which you can tell it to load the latest saved backup, but otherwise without any mod than enables player inventory backups you will loose all your items that were in your inventory.

**Comment by Ashley123477** [comment]
I believe im still having this in 2.1.9 1.16.5 with citadel 1.8.1
directly related to the player not the server, player has issues with something to do with stone statues. it throws a payload error, once the statues are removed it works fine.
![Ragnamod_VI_-_Minecraft_1 16 5_2022-01-10_7_16_08_PM](https://user-images.githubusercontent.com/26034936/148860824-b598e340-49a3-4b14-84cb-218fdf4cb273.png)

**Comment by Nagapito** [comment]
Also having same issue, same pack, Ragnamod 6....


My corpse only has a blindfold in it

**Comment by Nagapito** [comment]
It seems the issue is actually from OneProbe.
Maybe One probe cant handle packets greater then 1M, so... while still a "valid" statue, it crashes.

How to help with the situation, use command "/top need" to mark OneProbe as needed. This way OneProbe does not fetch the packet and client does not crash.

Also, keep in mind, that while the corpse will disappear after retrieving the items (in Rag6 pack), the statue is still there but invisible, exactly on the place of the corpse. You can notice it by the health bar of it provided by Neat mod. The statue needs to be mined or it will still cause issues once OneProbe is enabled again.
