### ISSUE TITLE
[1.12.2] Cyclops Cave Spawn

### ISSUE THREAD

**Issue by MokahTGS** [Alex-the-666/Ice_and_Fire#415]
Please add a y level config option for Cyclops caves.  We have them spawning up in the world which looks pretty odd.  Additional spawning options would also be welcomed.  Adding just general world spawn, like you have for Hypogrifs would be a good idea (configurable of course.)

Also, Cyclops have a lot of trouble with the fences in their lairs.  The get stuck on them all the time and just spin.

**Comment by PhoenixRiver** [comment]
Just started a new seed and a cyclops cave generated in the ocean just off the coast at sea level, it looked weird to me though (I've not seen one before though) but it seemed like two caves had spawn over the top of each other offset by about ten blocks - there was only one cyclops though.

**Comment by MokahTGS** [comment]
Yes after lots of worldgen testing both the cyclops cave and the medusa temple need some serious work.  Cyclops caves tend to favor rivers and medusa temples favor beaches.   Both of these are too small for the large structure to look good.

**Comment by PhoenixRiver** [comment]
Could the cyclops cave only spawn in hilly or mountainous regions so that his cave is actually spawned inside a hillside? (I think the double one I had spawned at the very mouth of a river that was underwater into an Ocean biome by that point (and the land was a plains type biome so it wouldn't have fit anyway... - the doubling could be fixed with a check to see that they didn't spawn if there is already one within x blocks).

And for the gorgon temple could it spawn them on the land side of the beach rather than the ocean side? (though that might be difficult to tell from the code end so maybe just have them centred on the beach? though maybe they already are? (difficult to tell what was underneath before the temple spawned!))

**Comment by AlexModGuy** [comment]
shouldnt happen in 1.4.0
