### ISSUE TITLE
fatal launch error from NoLakesInStructuresMixin [2.1.8]

### ISSUE THREAD

**Issue by joeyjumper94** [Alex-the-666/Ice_and_Fire#4156]
**Describe the bug**
using a mod based on code from this repository will prevent minecraft from launching

**To Reproduce**
1. download code from this repository
2. compile the code using gradlew
3. place the newly created jar file into your mods folder along with the latest version of citadel
4. try to launch your game

**Expected behavior**
I expect minecraft to finish 
launching

**Screenshots**
[latest.log](https://github.com/Alex-the-666/Ice_and_Fire/files/7017223/latest.log)

**Additional context**
I first discovered the issue when it happened after updating my own fork of this awesome mod.

**Comment by joeyjumper94** [comment]
the solution I found was to remove the file changes made by https://github.com/Alex-the-666/Ice_and_Fire/pull/4138

**Comment by TheBv** [comment]
~~When building the jar file via "gradlew build" the file generated when opening via e.g 7zip should include a "iaf.refmap.json" in the root directory.
Make sure you (re)import the gradle project to make sure the changes made by the pull request actually get loaded. If the file still isn't present please let me know :)~~
EDIT: I see where the issue is I'll immediately create a PR to fix it sorry for the inconvenience
