### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Charmanth** [Alex-the-666/Ice_and_Fire#4186]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
The Gorgon Statue issue is still apparent in 2.1.9  If a player is petrified the nbt overflows for them and crashes the player, but the server is fine.  I've had to rescue no less than 3 players from this fate :c  Also anyone looking at the statue crashes

**To Reproduce**
1: Go to Gorgon Temple
2: Get petrifried (likely with armor on)
3: crash and get logged out
4: Crash anytime you log back in
5: ????
6: Profit

**Expected behavior**
I expect the statue to just exist peacefully with no nbt overflow for either server or player.

**Screenshots**

**Additional context**
This is a heavily modded server, so I'm wondering if either armor with nbt data or modded stuff are to blame?  Also we're playing with keepInventory on.

**Comment by TheBv** [comment]
This definitely is related to mods that modify the players NBT data e.g add another inventory or armor etc... 
It's a rather difficult issue to debug since it requires mod dependencies (and I'm not yet certain which ones are causing the issue) and an entity with a lot of NBT data. 
My previous attempt at fixing this issue was simulating a network package with the same data and seeing if that'd cause any issues before creating the stone statue. Sadly that didn't seem to fix it.
I'll continue looking into other solutions...

**Comment by Charmanth** [comment]
Thanks for the comment and letting me know what's going on!  I hope you can find a fix that will work regardless of the mods involved.

**Comment by DaddyP1G** [comment]
Also having this issue.  I'm not sure if it helps to have a mod list
