### ISSUE TITLE
Okay not an issue, But we are getting no where on this

### ISSUE THREAD

**Issue by ModernGamingWorld** [Alex-the-666/Ice_and_Fire#4187]
How do we do custom Spawning for this Mod, We have been trying to add custom spawning of Dragons ECT for this mod and no matter who we ask or message on the Ice and Fire Discord that No one seems to have answer, if someone could show us or guide us on how to do this for Ice and Fire 1.16.5 we would be grateful.

**Comment by TheRanker** [comment]
[Generation.Dimensions]
        #True if using blacklists, false if using whitelists for dragons and structure gen.
        "Use Dimension Blacklist" = false
        #Whitelist dragon gen dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
        whitelistDimensionsDragons = ["minecraft:the_nether"]
        #Whitelisted feature(cyclops caves, hydra dens, etc) gen dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
        whitelistDimensionsFeature = ["minecraft:overworld"]
        #Whitelist mob spawn (troll, hippogryph, etc) dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
        whitelistDimensionsMobs = ["minecraft:overworld"]
        #Blacklisted dragon gen dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
        blacklistDimensionsDragons = ["minecraft:the_end"]
        #Blacklisted feature(cyclops caves, hydra dens, etc) gen dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
        blacklistDimensionsFeature = ["minecraft:the_end"]
        #Blacklisted mob spawn (troll, hippogryph, etc) dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
        blacklistDimensionsMobs = ["minecraft:the_end"]
thats for iceandfire-common.toml


this is the biomes for all the dragons currently 
{
  "biomes": [
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "minecraft:basalt_deltas"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "minecraft:nether_wastes"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "minecraft:warped_forest"
      }
    ]
  ]
}



this is using forge with iceandfire 2.1.9 and citadel 1.8.1
unable to get any dragons to spawn in nether.  ive tried multiple biomes and nothing works.

**Comment by TheBv** [comment]
I think I'll create a help file for this since it's long overdue and honestly not the most intuitive system at least without any explanation.
Basically we have two brackets. The way you've defined it @TheRanker works, but what you have defined is a list of biomes for which all conditions have to be met. So you're looking for a biome that has the registry name "minecraft:basalt_deltas", "minecraft:nether_wastes" AND "minecraft:warped_forest" and of course not a single biome meets these conditions.

We basically have an outer bracket with multiple inner brackets. The values inside the outer brackets are 'OR-ed' while the values in the inner ones are 'AND-ed' e.g this:
```json
{
  "biomes": [
    [
      {
        "type": "BIOME_DICT",
        "negate": false,
        "value": "overworld"
      },
      {
        "type": "BIOME_DICT",
        "negate": false,
        "value": "jungle"
      }
    ],
    [
      {
        "type": "BIOME_DICT",
        "negate": false,
        "value": "overworld"
      },
      {
        "type": "BIOME_DICT",
        "negate": false,
        "value": "mesa"
      }
    ]
  ]
}
```
translates to: We're only want x to spawn/generate in a biome that meets the following conditions:
(Is in the `overworld` AND a `jungle`) OR (Is in the `overworld` AND a `mesa`)
So to make things generate in the biomes you've specified all you'd have to do is modify your file to this: 
```json
{
  "biomes": [
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "minecraft:basalt_deltas"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "minecraft:nether_wastes"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "minecraft:warped_forest"
      }
    ]
  ]
}
```

BIOME_CATEGORY: refers to the category a biome is in (e.g ocean, taiga, jungle, extreme_hills,...)
REGISTRY_NAME: refers to the actual name of the biome e.g `minecraft:warped_forest`
BIOME_DICT: is a bit more complicated... Basically each biome has multiple dictionaries attached to it. E.g the biome `minecraft:gravelly_mountains` has the dictionary values: [`sparse`, `mountain`, `rare`, `overworld`] attached to it.
I'm uncertain if those values are listed for each biome somewhere...

Anyway I hope this helps! :)

**Comment by ModernGamingWorld** [comment]
@TheBv So I did what you said and nothing is spawning
{
  "biomes": [
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "byg:sythian_torrids"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "byg:wailing_garth"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "byg:weeping_mire"
      }
    ]
  ]
}

This is for Fire Dragon By The Way

**Comment by TheBv** [comment]
Nether biomes from this specific mod I think have the prefix `bygnether` [see](https://github.com/AOCAWOL/BYG-1/blob/7352d9bfa356a707ab50ced6734bb5ccf0f70560/src/main/java/corgiaoc/byg/BYG.java#L114). But this might not be the problem here. I can't really help you any further. All I can say is that it works without any other mods installed. 
Although I've noticed that the roosts tend to spawn on the nether roof which is something to be looked at imo...

**Comment by TheRanker** [comment]
> Nether biomes from this specific mod I think have the prefix `bygnether` [see](https://github.com/AOCAWOL/BYG-1/blob/7352d9bfa356a707ab50ced6734bb5ccf0f70560/src/main/java/corgiaoc/byg/BYG.java#L114). But this might not be the problem here. I can't really help you any further. All I can say is that it works without any other mods installed.
> Although I've noticed that the roosts tend to spawn on the nether roof which is something to be looked at imo...



> I think I'll create a help file for this since it's long overdue and honestly not the most intuitive system at least without any explanation.
> Basically we have two brackets. The way you've defined it @TheRanker works, but what you have defined is a list of biomes for which all conditions have to be met. So you're looking for a biome that has the registry name "minecraft:basalt_deltas", "minecraft:nether_wastes" AND "minecraft:warped_forest" and of course not a single biome meets these conditions.
> 
> We basically have an outer bracket with multiple inner brackets. The values inside the outer brackets are 'OR-ed' while the values in the inner ones are 'AND-ed' e.g this:
> 
> ```json
> {
>   "biomes": [
>     [
>       {
>         "type": "BIOME_DICT",
>         "negate": false,
>         "value": "overworld"
>       },
>       {
>         "type": "BIOME_DICT",
>         "negate": false,
>         "value": "jungle"
>       }
>     ],
>     [
>       {
>         "type": "BIOME_DICT",
>         "negate": false,
>         "value": "overworld"
>       },
>       {
>         "type": "BIOME_DICT",
>         "negate": false,
>         "value": "mesa"
>       }
>     ]
>   ]
> }
> ```
> 
> translates to: We're only want x to spawn/generate in a biome that meets the following conditions:
> (Is in the `overworld` AND a `jungle`) OR (Is in the `overworld` AND a `mesa`)
> So to make things generate in the biomes you've specified all you'd have to do is modify your file to this:
> 
> ```json
> {
>   "biomes": [
>     [
>       {
>         "type": "REGISTRY_NAME",
>         "negate": false,
>         "value": "minecraft:basalt_deltas"
>       }
>     ],
>     [
>       {
>         "type": "REGISTRY_NAME",
>         "negate": false,
>         "value": "minecraft:nether_wastes"
>       }
>     ],
>     [
>       {
>         "type": "REGISTRY_NAME",
>         "negate": false,
>         "value": "minecraft:warped_forest"
>       }
>     ]
>   ]
> }
> ```
> 
> BIOME_CATEGORY: refers to the category a biome is in (e.g ocean, taiga, jungle, extreme_hills,...)
> REGISTRY_NAME: refers to the actual name of the biome e.g `minecraft:warped_forest`
> BIOME_DICT: is a bit more complicated... Basically each biome has multiple dictionaries attached to it. E.g the biome `minecraft:gravelly_mountains` has the dictionary values: [`sparse`, `mountain`, `rare`, `overworld`] attached to it.
> I'm uncertain if those values are listed for each biome somewhere...
> 
> Anyway I hope this helps! :)

i have the dragons spawning in the nether perfectly fine using vanilla biomes. now to work on modded biomes.. also does the config accept multidimensions for the dragons? just verifying before  hit another brick wall or not.

many many thanks for that help btw!!!! worked fantastic

**Comment by TheRanker** [comment]
![dragons](https://user-images.githubusercontent.com/5889820/131578772-eb6d5516-c8cb-45d4-bd0e-6aa65726245a.jpg)

dragons confirmed working in BYG biomes in the nether using above as a guide.
