### ISSUE TITLE
Ice and Fire 1.16.3

### ISSUE THREAD

**Issue by redigamer** [Alex-the-666/Ice_and_Fire#4284]
Bug: 1.16.3 I installed Ice and Fire and Citadell for correct Versions, but when press play, and forge loads all things there is: 
Ice and Fire has failed to load in correctly... i dont know what i did wrong...
![p](https://user-images.githubusercontent.com/94397766/141837848-8ac8bcba-5de8-475a-9ea0-dca759d18786.PNG)

**Comment by Nyoom-Monster** [comment]
Are all your dependencies and the mod itself forge version? And is each mod and dependency updated/correct for the version of Minecraft that you're playing on?

https://www.minecraftforum.net/forums/support/java-edition-support/2786765-getting-java-lang-noclassdeffounderror-net

Here's a forum thread for someone who had the same error code as you. I found, when building mod packs, Googling the error codes and checking the status of the mod or resource file that forge said it had a problem with helps, and including "minecraft" after the error code (which you can sometimes copy and paste) can help direct you to solutions and guesses from other Minecraft users, as those error codes also sometimes correlate with other games/java programs that have nothing to do with Minecraft, and the explanation of what they mean and how to fix it may not work for your case/the language is too programmery for a newbie to understand (such as myself, and I can recognize a few terms, which sometimes help, and I recommend you learn some of them and the basics to save frustration and to better explain your problem to others).

And many people using the forge launcher will tell you this, but if all else fails, delete all the mods, and add them back one by one (generally you don't need to test if a dependency is breaking things, because in my experience, the mods with dependencies tend to be the ones that function pretty well/are popular, and so the dependencies are usually pretty sound [they kinda have to be because they are required to make the mod/mods work], but sometimes in rare cases, they will still break a modpack.) When that happens, look up the error code+minecraft+dependency (you can substitute the dependency for a mod, too) and try to troubleshoot it yourself if you can. You may ultimately have to remove the mod from your pack in the end, but you'll still gain experience, and I would hope you would retain at least some of the information you found.

Alternatively, build the pack in a different Minecraft version, try using fabric instead (not all forge mods are ported to fabric, and vice versa), find someone to build/fix the pack for you, or help you do it, or use the "repair profile" function on the overwolf forge launcher (PC program, I highly recommend it, and it's really great at keeping you from installing mod versions and forge/fabric versions of mods that won't work with your chosen Minecraft and launcher options.

Also, make sure you're using the required version of forge for the mods you have, and get rid of any that require versions that conflict too much. I suggest using the newest version of forge launcher you can for the mods you have/Minecraft version you are playing on, as most mods for that version won't require a later forge version, or an earlier forge version, than what is available for the version of Minecraft you're running.

Also, Optifine helps, but be warned, you need to download it on the forge website instead (MC version specific), and add it to your mods folder where the other ones are for that pack (if you get a crash that allows you the option to open the mods folder, try it and make sure to remember how to find those folders in your computer (my packs, for instance, are in My PC>Local Disc C>users>admin>curseforge/.minecraft>Instances

Make sure to name your pack first. The same rules above for other mod/dependencies (Optifine is both) apply to this. You need Optifine for a few mods out there, and for shaders and resource packs.

If all that fails, start over again with a new "custom profile" on forge.

Oh, and make sure Ice and Fire and its dependencies are in the correct folders, and that the folders are named correctly. You can find guides on this, or look at the files on your computer for a popular, well-working mod pack.

Good luck!
