### ISSUE TITLE
Entity Ticking server crash when using dragonfire forge [1.9.1-1.12.2]

### ISSUE THREAD

**Issue by slader007** [Alex-the-666/Ice_and_Fire#4529]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Server crashes when trying to use dragonfire forge with dragon

**To Reproduce**
1. join server
2. place dragon next to forge
3. crash after a few seconds

**Expected behavior**
Not to crash 

**Screenshots**

**Additional context**
Already tried uninstalling thaumcraft Playing on RAD modpack

[crash-2022-06-14_01.26.48-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/8898042/crash-2022-06-14_01.26.48-server.txt)

**Comment by DigitalWendigo** [comment]
1.12.2 is no longer supported. 
In adition to that, have you modified the modpack in any way? 
I'd suggest taking this issue to the developer of the RAD modpack. 
Since they made the pack, they probably fine tuned it to make everything work. Altering such a modpack can cause various issues if you don't know what's been done.
