### ISSUE TITLE
On a Aternos Server server crashes on launch due to ice and fire 

### ISSUE THREAD

**Issue by Noscw** [Alex-the-666/Ice_and_Fire#4574]
I have been playing on a server with some friends for about a week now. ever since last night, Joining the server instantly results in it crashing. The Aternos Mods said that its a problem with ice and fire and to contact the creator of the mod. here's the log of the server --> https://mclo.gs/XcyTFjY

**Comment by TheBv** [comment]
~~Not sure why they told you that this is an issue with Ice and fire when it clearly states `Failed loading config file cucumber-client.toml of type CLIENT for modid cucumber` which tells me this has to do with the cucumber mod. I'd suggest making sure that the config file `cucumber-client.toml` exists or try to delete and replace it.~~

**Comment by Noscw** [comment]
I don’t have a cucumber mod so there is no cucumber-client.toml file also I looked through the log and didn’t see where it said that

**Comment by TheBv** [comment]
Sorry my mistake I've gotten this messed up with another log file I had open. I'm sorry for wasting your time because of this..
This has been fixed and is available in the latest snapshot. https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot
I want to fix a couple more things before I talk with alex about publishing a new fixed version to curseforge.

**Comment by Noscw** [comment]
Ok thanks
