### ISSUE TITLE
HORRID Server crashing due to missing class in Ice & Fire [2.1.10 LATEST]

### ISSUE THREAD

**Issue by Burchard36** [Alex-the-666/Ice_and_Fire#4606]
Bug: Any stage 5 dragon i run into on my server, instantly crashes it due to a pathfinding error... im now having to remove ice and fire and my server is just stuck in an endless loop of crashing, as when the server crashed my player crashed near the level 5 den

This issue has been plaguing Ice and Fire for a long time now, in fact there's an original report reported  on #4569 

Figured i would open an issue as well, as this is a rather serious issue

The issue seems to lie in the dragon getting stuck when Ice and fire runs with mods that may generate things inside the next (Eg a spawner dungeon or similar) and it in turn for some reason wakes the level 5 up, makes it go fly to the roof of the den and getting "stuck" from there, endlessly crashing the server

This has happened 3 times today on a fresh modpack and fresh pre-genned server, one time i was able to get very close to the dragon that was crashing me, see here: 
![image](https://user-images.githubusercontent.com/48583030/182535801-7a07d8a1-b99c-43fb-903e-97b1f433aa6f.png)

When the dragon got to this position, the server endlessly crashed, however, this one was on a debugging server so /kill @e was viable here. 

**To Reproduce**
1. Run Ice & Fire
2. Mine underground to a level 5 nest, or find one in a cave
3. infinite crash loop unless you kill all entities on the servers... Pretty sure its clear that's not an option 
4. Its a 50/50 Chance, not uncommon but also hard to trigger (I assume it happens every level 5s nest i run into, in fact the error actually tells me when im next to a level 5 nest because of the server crash haha)

**Expected behavior**
The class should be existing in the project, I feel like its a rather straightforward issue 

**Screenshots**
https://paste.md-5.net/adanutukiq.pl

**Additional context**
Im running this in tandem with 140 other mods, modpack is here: https://www.curseforge.com/minecraft/modpacks/chaos-and-heart

As stated, im on the absolute newest version of everything for forge 1.16.5 as well as Ice and Fire and its depndency, i just slapped this modpack together last night and no new updates for anything has happened since then

**Comment by Burchard36** [comment]
![image](https://user-images.githubusercontent.com/48583030/182537895-0c652cb4-b838-42d4-8668-abc19535d54c.png)
Had to cheat, but the server finally stopped crashing

Found his nest, and there seems to be these blocks here, perhaps these messed with his pathfinding somehow? However this one is the first stage 4 i found that made me crash, other 2 were stage 5s

Seems the crashing has stopped for now, but im certain it will be back

**Comment by Burchard36** [comment]
Im back with more information:

~~So the server will crash 3 times exactly with this message: https://paste.md-5.net/utidoyociw.pl (Same one as before)~~

Just had the server crash for the 4th time while typing this, reallly frustrating :/ https://paste.md-5.net/utidoyociw.pl

~~After the 3 times of crashing all is normal? Not sure why after 3 times it will run fine, but its something ive noticed, had it happen 2 more times after posting the last reply~~

The client crashes with a StackOverFlow error, the server is not OOM, unless it OOM's when Ice of Fire fails pathfinding? Ptero doesnt let me know of any OOM errors and i have 16gb of ram for the server

UPDATE: After it stopped crash looping, i eventually received this error a few times in my console, and no crashes: https://paste.md-5.net/itaqiqokix.pl

UPDATE Pt2: Jesus christ, after a while now, the message above crashed my server: https://paste.md-5.net/foyenaruyo.pl

Tried installing a fresh jar, no avail

**Comment by TheBv** [comment]
This crash has been plaguing the mod for quite some time. I was hoping I had addressed it in the 2.1.10 update.
The issue is that I've never encountered this crash by myself. I even went ahead and installed your modpack and it's not happening for me. Some people just seem to be experiencing the issue and some aren't. 
I went ahead and further updated some code pieces which are the only things left I could imagine causing these issues.
If you can I'd be cool if you could grab the latest snapshot from here https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot 
I think you should be able to get away with just updating the sever jar. Can't promise that though since the snapshot jar has a different version tag.
Let me know if this fixes the issue for you. If not I'll see what I can further come up with...

**Comment by Burchard36** [comment]
> This crash has been plaguing the mod for quite some time. I was hoping I had addressed it in the 2.1.10 update. The issue is that I've never encountered this crash by myself. I even went ahead and installed your modpack and it's not happening for me. Some people just seem to be experiencing the issue and some aren't. I went ahead and further updated some code pieces which are the only things left I could imagine causing these issues. If you can I'd be cool if you could grab the latest snapshot from here https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot I think you should be able to get away with just updating the sever jar. Can't promise that though since the snapshot jar has a different version tag. Let me know if this fixes the issue for you. If not I'll see what I can further come up with...

Before i update, do you want admin on my pterodactyl panel to test this on the current production build before i try the latest snapshot? I cant really hand over server files, its 10GB of pre-genned chunks haha

I can give you coords of where the dragon is that crashing the server, was still doing it last night so i logged out in that area and pre-genned the world overnight

May be easier to talk on discord about that: Dalton#0404

**Comment by Burchard36** [comment]
Tried the new snapshot, unfortunately the same issue: https://paste.md-5.net/yoqiwiqefo.pl

I have a backup of the state where the server was crashing, in fact i stopped the server and backed up right when i crash, so the world so the server should still be in a errored state, its 6.3GB so likely sending that direct is gonna be an issue haha

**Comment by TheBv** [comment]
So after some investigating this seems to have to do with the mod `bigbrain`.
In general any mod that adds entity pathfinding behavior to mobs will most likely crash the server due to the pathfinding being threaded and mixins not working too well with them.
I wrote up a quick fix for that specific mod here: https://github.com/Alex-the-666/Ice_and_Fire/wiki/Incompatibility-with-the-bigbrain-mod
Let me know if that fixes it for you :)

If anyone else is experiencing similar issues and don't have the mod installed I'd encourage you to look for any mods that add new entity pathfinding behaviors.

Thank you so much for providing me with all the files and stuff @Burchard36 probably wouldn't have figured this out as quickly without your help :D

**Comment by TheBv** [comment]
Should hopefully been fixed for good now with 57a72de
