### ISSUE TITLE
Ticking Entity Crash from Hippogryphs

### ISSUE THREAD

**Issue by IIMarabarII** [Alex-the-666/Ice_and_Fire#461]
I've been experiencing problems with the Hippogryphs causing a ticking entity crash client-side, both on Singleplayer and Multiplayer.  I have tried to recreate this type of crash in testing, but I could never get it to consistently crash so I don't know what really causes the ticking error with the Hippogryph.

Here's a link to the crash report...
[Crash Report](https://pastebin.com/Q9uFq14U)

**Comment by GundunUkan** [comment]
Having the same issue. Didn't know it was the hippos, thanks!

**Comment by AlexModGuy** [comment]
caused by primitive mobs, they have to fix this

**Comment by MAndrewSprong** [comment]
Still crashing. Need to move datamanager code from EntityInit override into constructor so that data manager based calls don't encounter race condition. See: http://www.minecraftforge.net/forum/topic/60543-solved1121-entitydatamanager-errors-driving-me-crazy/

DataManager fields have to be instantiated first. e.g. If they don't exist after construction then EntityInit will bork when trying to set them.

This is the case for most entities in this mod.
