### ISSUE TITLE
Dragon attacks can be dismounted

### ISSUE THREAD

**Issue by estradus** [Alex-the-666/Ice_and_Fire#462]
When dragons pick you up for their bite attacks, it counts as riding a mount (you can see the mount hp bar) - so you can just sneak to dismount it to avoid the attack. 

Being able to escape the attack somehow should be an option, but it would make more sense to do that by attacking the head or something during the attack: deal enough damage before it thrashes or tosses and it'll just drop you, or something, would be cool.  Being able to escape just by saying "oh hey let me down now" seems like cheating.

**Comment by GundunUkan** [comment]
I agree, it's like dragons have a very weak bite force, weak enough for you to open their jaws and jump out. It's not THAT bad though, it's not like you're out of harm's way, since typically the following attack is a fire/ice breath that finishes you off. But yeah, I support the idea of having to hit its head or something in order to get away.

**Comment by AlexModGuy** [comment]
not an issue
