### ISSUE TITLE
Baby mobs (hostile and passive) not appearing, stone statues show as pigs.

### ISSUE THREAD

**Issue by jollyjoee** [Alex-the-666/Ice_and_Fire#4699]
Anyone else having the issue when they have ice and fire installed on their server, baby mobs (animals and hostile) appear as adults (even if they move and sound like babies). Stone statues all appear as pigs too but when you break them, you get the corresponding mob statue.

I know that Ice and fire and/or citadel could be causing this issue cause when i removed them from my server's mod list, everything went back to normal.

Using 2.1.11 ice and fire and citadel 1.8.1 both client and server side.

Add: Single player works fine. Narrowed it down to citadel 1.8.1 server-side.

Single player and server have both the same mods but singleplayer is okay and my server hase the issue.

Add: All dragons around the world are babies, no adults.

Expected behavior
Baby mobs appear instead of adults

**Comment by TheBv** [comment]
Another user has reported a similar issue on the discord server.
In their case it was the caves and cliffs backport mod that was causing issues.
After investigating this mod seems to register a new property to all `LivingEntities` to handle the frozen state.
This however causes de-synchronizations between the client and server. 
There most likely are other mods that do similar things so it won't just be the caves and cliffs backport that causes this.
There's nothing I can really do about this/ I won't change pieces of the code because another mod is doing things incorrectly.
