### ISSUE TITLE
[Bug]: 1.16.5 ice and fire mobs crashes game(ticking entity)

### ISSUE THREAD

**Issue by Enkvaros** [Alex-the-666/Ice_and_Fire#4760]
### What happened?

Sometimes randomly game crashes and crash report say ticking entity I encountered 2 different mob with 2 crash Hippogryph and ice dragon.

### Minecraft Version

1.16

### Ice and Fire version

iceandfire-2.1.11-1.16.5

### Citadel version

citadel-1.8.1-1.16.5

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Enkvaros** [comment]
first crash: ice dragon

[crash-2023-02-27_10.59.31-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10854284/crash-2023-02-27_10.59.31-server.txt)

**Comment by Enkvaros** [comment]
second crash: Hippogryph
[crash-2023-02-28_21.30.34-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10854286/crash-2023-02-28_21.30.34-server.txt)

**Comment by Enkvaros** [comment]
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/10854300/latest.log)

**Comment by Enkvaros** [comment]
And sorry about sending crash reports with comment when I attached into post it said too long

**Comment by ChaoticDusk** [comment]
I'm having the same issues. I thought it was an issue with shaders since I'd just started using that but it crashes even without that. Mine happened because of a hippogryph(with shaders) and a fire dragon(without shaders). I wish I knew what it was but I'm trying to figure it out too and I figured it might be nice to know that you're not the only one experiencing this cause I was definitely concerned that this was just a me problem.

**Comment by ChaoticDusk** [comment]
I made a previous comment on this cause I've been having the same issue and deleted because I think I found something that works for me. I don't know if you're playing with the latest version or not but if you are try rolling it back to 2.1.9 and see how that works. So far it hasn't crashed for me but I'm not sure if that will change. Its as good a shot as any though I suppose.

**Comment by TheBv** [comment]
Try out the latest snapshot and let me know if that fixes things
https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/latest-snapshot

**Comment by Enkvaros** [comment]
I try to summon a dragon in a flat test world. Game only crashes when dragon attempt to "fly" I guess it will be same for Hippogryph problem is in the flying animations I think. Now I'm going to try the latest snapshot right away.

**Comment by Enkvaros** [comment]
Yes latest snapshot solves the bug thanks man

**Comment by ChaoticDusk** [comment]
> Try out the latest snapshot and let me know if that fixes things https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/latest-snapshot

That fixed things for me too, thank you so much!

**Comment by Enkvaros** [comment]
Ok I am closing this issue page then
