### ISSUE TITLE
[Bug]: Second layer of minecraft skin going over armour

### ISSUE THREAD

**Issue by JusOllie** [Alex-the-666/Ice_and_Fire#4826]
### What happened?

When i put on most armours from the mod the second layer of my skin sticks out over the armour.

### Minecraft Version

1.16

### Ice and Fire version

iceandfire-2.1.12-1.16.5

### Citadel version

citadel-1.8.1-1.16.5

### Relevant log output

No log output since the game still works.

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I've noticed this issue as well when I ported this mod to 1.17/1.18
I won't be fixing this though since the models get messed up quite a bit if I make them like the default minecraft armor models (see #4794)
So they will need to get reworked completely / properly which I don't intend on doing and might be done in a future update anyways.

**Comment by GizmoTheMoonPig** [comment]
I actually had a similar issue when porting rats to 1.19 (plague doctor masks have the same issue), and the good news is that theres a workaround if youre interested. All you have to do is simply unrender the hat layer if the problem helmet is on the player's head. This is all it takes to set up: https://github.com/AlexModGuy/Rats/blob/1.19/src/main/java/com/github/alexthe666/rats/client/events/ForgeClientEvents.java#L152-L160
