### ISSUE TITLE
[Bug]: mobs won't spawn using the mod terralith in 1.18.2 and trolls not spawning

### ISSUE THREAD

**Issue by Spino555** [Alex-the-666/Ice_and_Fire#4860]
### What happened?

mobs rarely spawn it seams sea serpents, hydras, other things, spawned in abundance before now i can't find them in any world also I notices that trolls just don't spawn with no mods with mods they just don't spawn for me.

### Minecraft Version

1.18

### Ice and Fire version

latest as of may 2, 2023

### Citadel version

latest as of may 2, 2023

### Relevant log output

```shell
I don't know what log output means sorry
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by FelixAndre** [comment]
had same issue only couple mermaids spawned in my world

**Comment by CotardsSolution** [comment]
Hello, for future reference, a log output is basically if a game crashes (Which in this case it didn't, so you don't have to worry about it for this specific issue), Minecraft creates what's called a "Crash log", which means a long and detailed report of the error that led up to the crash. Once again, don't worry about it for this issue, but remember this for future reference :)

**Comment by Spino555** [comment]
Thanks I will remember that.

**Comment by qqbone** [comment]
Terralith doesn't really organize their biomes by what Ice and Fire looks for. Aka hot/cold or dessert/swamp/savanna/mountain extensions. We need to manually add the biomes to spawn config folder for Ice and Fire's monsters individually. Some work, some don't because vanilla like biomes still spawn with Terralith you'll get a glimpse of ice and fire mobs every once and a while.
So Terralith or IceandFire need a compat. There's also things like incontrol if you're adding monsters for certain depths. It's the same for structures as well depending on the mod.

Someone released some configs for dragons in the Terralith discord, although I haven't gone through them entirely and matched up the biomes I'll be taking a look and compiling my own configs to add.
These are what they released take a look and it's the example on how things need to be written and see if you want them to match up this way, it can be used for skeletons and dragons.
lightning dragon:
https://pastebin.com/ANHnybgk
fire dragon:
https://pastebin.com/zFA6tVVU
ice dragon:
https://pastebin.com/f26Due9Y
So unless Terralith writes their biomes to be organized in recognition to Ice and Fire mobs look for, it's a manual add in configs or using tools like incontrol to spawn them in. If you ever make a modpack or add to one world/biome overhauls are always a lot of work unless someone has already released a compat pack/configs for it.
I'm still going though my own configs, if I finish mine, I'll publish it as a config on curseforge and respective discords. I came looking for how dragon dens are supposed to spawn since Terralith overrides the underground too.

**Comment by catter1** [comment]
> So unless Terralith writes their biomes to be organized in recognition to Ice and Fire mobs look for, it's a manual add in configs or using tools like incontrol to spawn them in.

Would Terralith registering their biomes into the Forge biome registry and using Forge biome tags be enough? Or would more need to be done for Ice and Fire to recognize them?

**Comment by qqbone** [comment]
I would assume so, I know biome organization changed past 1.16.5 and I'm sure the 1.18 release of iceandfire follows the current biome organization or they wouldn't spawn at all. Modded biomes can sometimes be a real pain.
