### ISSUE TITLE
[Bug]: Tamed Hippogriff falling through world

### ISSUE THREAD

**Issue by Maikx** [Alex-the-666/Ice_and_Fire#4924]
### What happened?

If your tamed hippogriff is sitting down and you mount and dismount fast enough it will fall through the world and die in the void.

![Bug](https://github.com/AlexModGuy/Ice_and_Fire/assets/51028649/19ea6892-f477-4283-ab10-e1cb12fbd1a9)

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2

### Citadel version

citadel-1.11.3-1.18.2

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by luchothv** [comment]
Hi, same issue here, exactly the same. You found any solution ?

**Comment by thedada333** [comment]
I have done some tests in creative, i think it has to do with the animation the hyppogriph does whenever you mount him while he was sitting: as long as the animation is running if you dismount the code doesn't check for collisions with blocks, so it falls in the void (it also happens if you command him to sit/get up with the stick and you dismount too quickly)

**Comment by SiverDX** [comment]
this should be fixed in the latest version by not setting nophysics to true 
(not sure if it was added to 1.18)
