### ISSUE TITLE
[1.19.2] nothing from the mod is spawning

### ISSUE THREAD

**Issue by Thaumist** [Alex-the-666/Ice_and_Fire#5141]
playing on 1.19.2, the latest update, and even with the mod alone with citadel nothing is spawning. I'd fly thousands of blocks around and no structures or dragons. Config says everything is enabled so not sure what's wrong.

**Comment by SiverDX** [comment]
check your biome config files

**Comment by DigitalWendigo** [comment]
> playing on 1.19.2, the latest update, and even with the mod alone with citadel nothing is spawning. I'd fly thousands of blocks around and no structures or dragons. Config says everything is enabled so not sure what's wrong.

May need a bit more information than this, since it seems to work as intended on my end. 
Even with alternative world generators, the structures still spawn. 

- Check your Biome Config files as SiverDX mentioned, located in: config>iceandfire>(there will be several .json files in this folder.) 
- You said no other mods besides IaF and Citadel, does that also mean you're not using any performance mods? 
- Did you install the mods in a new world, or an existing one? 
- Provide a Log file, it may contain useful information.

Cheers!

**Comment by Thaumist** [comment]
(just a heads up I'm pretty naive when it comes to files and code Knowhow so sorry if I'm difficult at all)

When I added the mod to my mod folder it was with mods like immersive engineering, Oculus, Rubidium, Biomes youll go, couple of natural spawn structure mods (I don't use Optifine). I then loaded a new world and noticed no structures or mobs from IaF were appearing after traveling for a while. I then removed everything other than Citadel and IaF and started a new world to test if it was just a mod conflict and still nothing was spawning.

another problem on my end with the configs is that all those JSON files are class files. 
![A3](https://github.com/AlexModGuy/Ice_and_Fire/assets/158415839/380711f7-bed3-4960-b446-c06392ea35cd)

**Comment by DigitalWendigo** [comment]
Did you unpack the .jar file? 
You're supposed to just chuck it in the mods folder, and the .json files will generate, including the biome folder.

**Comment by Thaumist** [comment]
no, I keep it zipped in my mods folder

**Comment by gpylypchuk** [comment]
hey, @Thaumist do you find a solution for this?
