### ISSUE TITLE
Sirens lure you for eternity(need confirmation)

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#705]
When you are under the affect of the siren's lure and are trapped and can't get to the siren, he will sing his song forever since you will never get close for the next stage.

**Comment by Tyaeth** [comment]
This seems to have happened to me. I was travelling through an underground passage and a siren rock was above the passage. The siren started luring me towards it but because of the roof of the passage I wasn't able to get to the siren, and because being pulled bounced me around so much I wasn't able to break any of the blocks obstructing me.

**Comment by laserlemons** [comment]
I also had this happen. I got stuck on a corner forever until I went to creative mode and flew away. Using version 1.6.0.

**Comment by AlexModGuy** [comment]
fixed
