### ISSUE TITLE
Cockatrice doesn't follow

### ISSUE THREAD

**Issue by GundunUkan** [Alex-the-666/Ice_and_Fire#879]
If you leave a cockatrice sitting and then relog and tell it to follow you it gets up but continues to stay stationed.

**Comment by DarianLStephens** [comment]
I've just experienced the same issue. I had my Cockatrice sitting in my house, I logged off for the night, and when I reloaded the world, it wouldn't move on its own.
Whether I set it to 'Patrol' or 'Follow', it just stayed put.
Oddly enough, it would sometimes look like it was sitting while in the 'Follow' mode, and switching made it stand back up.
This is really unfortunate, since I was hoping to have some help clearing some caves. I hope I won't need a new cockatrice each load...
EDIT: Well, thankfully, putting the Cockatrice in to 'Follow' mode then reloading the world fixes it.

**Comment by AlexModGuy** [comment]
fixed
