### ISSUE TITLE
Stone statue dies, and can't sleep near statues

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Ice_and_Fire#959]
Destroying the stone statue with silk touch, repeating installation will damage the stone statue and eventually die.
Also, perhaps I can not sleep near monsters' stone statues.
I think it is difficult, but how about making a stone statue a different entity?

**Comment by BlueWither** [comment]
Oh,this problem has nothing to do with Mowzie's Mobs

**Comment by Iashar** [comment]
I'd love to see this happen as well, I've got a bunch of tiny 'bat statues' now, and I love them, but I can't move them cause they're at half a heart and attempting to move them outright kills them. You seem to freeze their health at a certain point, but it never regenerates, armour stands don't lose health when attacked, but act as entities, just like statues. Main difference being, your statues actually seem to contain their original inhabitants, and die with them if you damage them too much.


Edit: Due to the mobs still being 'alive' inside their stone skin, some in house critters react to them in an offensive manner. My tame death worms for example, are attacking this creeper statue.
![screenshot 2018-08-25 19 33 22](https://user-images.githubusercontent.com/15375524/44624253-c8fa9f80-a89d-11e8-815c-58b68b95a8c3.png)
